//*
// @file db/v1/database.proto
// @description The definitive gRPC contract for the go-sqlite-proxy service.
//
// ARCHITECTURAL DESIGN:
//
// 1. DUAL TRANSACTION MODELS:
//    - Streaming (Bidirectional): Best for short, interactive sessions where the
//      connection lifespan equals the transaction lifespan. Automatic rollback on disconnect.
//    - Unary (ID-Based): Best for stateless HTTP clients or long-running workflows where
//      holding a TCP connection open is brittle. Requires manual 'Begin'/'Commit' and
//      relies on server-side Timeouts (TTL) to clean up "Zombie" transactions.
//
// 2. TYPE SAFETY (SPARSE HINTS):
//    Since JSON/Protobuf lacks native support for some SQLite types (like BLOBs or
//    large Integers), we use a "Hint" system. The client sends data as standard JSON
//    types but provides a mapping (e.g., "param 0 is a BLOB") so the server knows
//    to decode Base64 before hitting the DB.
//
// 3. ERROR FIDELITY:
//    We map native C SQLite result codes to a Proto Enum (`SqliteCode`). This allows
//    clients to programmatically react to specific errors (e.g., retrying on SQLITE_BUSY)
//    without parsing error string messages.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: db/v1/db_service.proto

package dbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sqlite-server/internal/protos/db/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "db.v1.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceQueryProcedure is the fully-qualified name of the DatabaseService's Query RPC.
	DatabaseServiceQueryProcedure = "/db.v1.DatabaseService/Query"
	// DatabaseServiceQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// QueryStream RPC.
	DatabaseServiceQueryStreamProcedure = "/db.v1.DatabaseService/QueryStream"
	// DatabaseServiceTransactionProcedure is the fully-qualified name of the DatabaseService's
	// Transaction RPC.
	DatabaseServiceTransactionProcedure = "/db.v1.DatabaseService/Transaction"
	// DatabaseServiceBeginTransactionProcedure is the fully-qualified name of the DatabaseService's
	// BeginTransaction RPC.
	DatabaseServiceBeginTransactionProcedure = "/db.v1.DatabaseService/BeginTransaction"
	// DatabaseServiceTransactionQueryProcedure is the fully-qualified name of the DatabaseService's
	// TransactionQuery RPC.
	DatabaseServiceTransactionQueryProcedure = "/db.v1.DatabaseService/TransactionQuery"
	// DatabaseServiceCommitTransactionProcedure is the fully-qualified name of the DatabaseService's
	// CommitTransaction RPC.
	DatabaseServiceCommitTransactionProcedure = "/db.v1.DatabaseService/CommitTransaction"
	// DatabaseServiceRollbackTransactionProcedure is the fully-qualified name of the DatabaseService's
	// RollbackTransaction RPC.
	DatabaseServiceRollbackTransactionProcedure = "/db.v1.DatabaseService/RollbackTransaction"
	// DatabaseServiceExecuteTransactionProcedure is the fully-qualified name of the DatabaseService's
	// ExecuteTransaction RPC.
	DatabaseServiceExecuteTransactionProcedure = "/db.v1.DatabaseService/ExecuteTransaction"
)

// DatabaseServiceClient is a client for the db.v1.DatabaseService service.
type DatabaseServiceClient interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for this RPC.
	// For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse]
	// *
	// Starts a new transaction context on the server and returns a 'transaction_id'.
	// The server holds the connection open in memory until Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Commits the transaction associated with the ID and releases server resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
}

// NewDatabaseServiceClient constructs a client for the db.v1.DatabaseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		query: connect.NewClient[v1.QueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		queryStream: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
			connect.WithClientOptions(opts...),
		),
		transaction: connect.NewClient[v1.TransactionRequest, v1.TransactionResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
			connect.WithClientOptions(opts...),
		),
		beginTransaction: connect.NewClient[v1.BeginTransactionRequest, v1.BeginTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceBeginTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
			connect.WithClientOptions(opts...),
		),
		transactionQuery: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		commitTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceCommitTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
			connect.WithClientOptions(opts...),
		),
		rollbackTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceRollbackTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
			connect.WithClientOptions(opts...),
		),
		executeTransaction: connect.NewClient[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceExecuteTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	query               *connect.Client[v1.QueryRequest, v1.QueryResult]
	queryStream         *connect.Client[v1.QueryRequest, v1.QueryResponse]
	transaction         *connect.Client[v1.TransactionRequest, v1.TransactionResponse]
	beginTransaction    *connect.Client[v1.BeginTransactionRequest, v1.BeginTransactionResponse]
	transactionQuery    *connect.Client[v1.TransactionQueryRequest, v1.QueryResult]
	commitTransaction   *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	rollbackTransaction *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	executeTransaction  *connect.Client[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse]
}

// Query calls db.v1.DatabaseService.Query.
func (c *databaseServiceClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.query.CallUnary(ctx, req)
}

// QueryStream calls db.v1.DatabaseService.QueryStream.
func (c *databaseServiceClient) QueryStream(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.queryStream.CallServerStream(ctx, req)
}

// Transaction calls db.v1.DatabaseService.Transaction.
func (c *databaseServiceClient) Transaction(ctx context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse] {
	return c.transaction.CallBidiStream(ctx)
}

// BeginTransaction calls db.v1.DatabaseService.BeginTransaction.
func (c *databaseServiceClient) BeginTransaction(ctx context.Context, req *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return c.beginTransaction.CallUnary(ctx, req)
}

// TransactionQuery calls db.v1.DatabaseService.TransactionQuery.
func (c *databaseServiceClient) TransactionQuery(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.transactionQuery.CallUnary(ctx, req)
}

// CommitTransaction calls db.v1.DatabaseService.CommitTransaction.
func (c *databaseServiceClient) CommitTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.commitTransaction.CallUnary(ctx, req)
}

// RollbackTransaction calls db.v1.DatabaseService.RollbackTransaction.
func (c *databaseServiceClient) RollbackTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.rollbackTransaction.CallUnary(ctx, req)
}

// ExecuteTransaction calls db.v1.DatabaseService.ExecuteTransaction.
func (c *databaseServiceClient) ExecuteTransaction(ctx context.Context, req *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return c.executeTransaction.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the db.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for this RPC.
	// For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error
	// *
	// Starts a new transaction context on the server and returns a 'transaction_id'.
	// The server holds the connection open in memory until Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Commits the transaction associated with the ID and releases server resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(databaseServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceQueryStreamProcedure,
		svc.QueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionHandler := connect.NewBidiStreamHandler(
		DatabaseServiceTransactionProcedure,
		svc.Transaction,
		connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceBeginTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceBeginTransactionProcedure,
		svc.BeginTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionQueryProcedure,
		svc.TransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCommitTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceCommitTransactionProcedure,
		svc.CommitTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRollbackTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceRollbackTransactionProcedure,
		svc.RollbackTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecuteTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceExecuteTransactionProcedure,
		svc.ExecuteTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/db.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceQueryProcedure:
			databaseServiceQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceQueryStreamProcedure:
			databaseServiceQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionProcedure:
			databaseServiceTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceBeginTransactionProcedure:
			databaseServiceBeginTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryProcedure:
			databaseServiceTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceCommitTransactionProcedure:
			databaseServiceCommitTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceRollbackTransactionProcedure:
			databaseServiceRollbackTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceExecuteTransactionProcedure:
			databaseServiceExecuteTransactionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Query is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.QueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Transaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.BeginTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.CommitTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.RollbackTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.ExecuteTransaction is not implemented"))
}
