//*
// @file db/v1/database.proto
// @description The definitive gRPC contract for the sqlite-server service.
//
// ARCHITECTURAL DESIGN:
//
// 1. DUAL TRANSACTION MODELS:
//    - Streaming (Bidirectional): Best for short, interactive sessions where
// the connection lifespan equals the transaction lifespan. Automatic rollback
// on disconnect.
//    - Unary (ID-Based): Best for stateless HTTP clients or long-running
// workflows where holding a TCP connection open is brittle. Requires manual
// 'Begin'/'Commit' and relies on server-side Timeouts (TTL) to clean up
// "Zombie" transactions.
//
// 2. TYPE SAFETY (SPARSE HINTS):
//    Since JSON/Protobuf lacks native support for some SQLite types (like BLOBs
// or large Integers), we use a "Hint" system. The client sends data as standard
// JSON types but provides a mapping (e.g., "param 0 is a BLOB") so the server
// knows to decode Base64 before hitting the DB.
//
// 3. ERROR FIDELITY:
//    We map native C SQLite result codes to a Proto Enum (`SqliteCode`). This
// allows clients to programmatically react to specific errors (e.g., retrying
// on SQLITE_BUSY) without parsing error string messages.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: db/v1/db_service.proto

package dbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sqlite-server/internal/protos/db/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "db.v1.DatabaseService"
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "db.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceQueryProcedure is the fully-qualified name of the DatabaseService's Query RPC.
	DatabaseServiceQueryProcedure = "/db.v1.DatabaseService/Query"
	// DatabaseServiceQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// QueryStream RPC.
	DatabaseServiceQueryStreamProcedure = "/db.v1.DatabaseService/QueryStream"
	// DatabaseServiceTransactionProcedure is the fully-qualified name of the DatabaseService's
	// Transaction RPC.
	DatabaseServiceTransactionProcedure = "/db.v1.DatabaseService/Transaction"
	// DatabaseServiceBeginTransactionProcedure is the fully-qualified name of the DatabaseService's
	// BeginTransaction RPC.
	DatabaseServiceBeginTransactionProcedure = "/db.v1.DatabaseService/BeginTransaction"
	// DatabaseServiceTransactionQueryProcedure is the fully-qualified name of the DatabaseService's
	// TransactionQuery RPC.
	DatabaseServiceTransactionQueryProcedure = "/db.v1.DatabaseService/TransactionQuery"
	// DatabaseServiceTransactionQueryStreamProcedure is the fully-qualified name of the
	// DatabaseService's TransactionQueryStream RPC.
	DatabaseServiceTransactionQueryStreamProcedure = "/db.v1.DatabaseService/TransactionQueryStream"
	// DatabaseServiceTransactionSavepointProcedure is the fully-qualified name of the DatabaseService's
	// TransactionSavepoint RPC.
	DatabaseServiceTransactionSavepointProcedure = "/db.v1.DatabaseService/TransactionSavepoint"
	// DatabaseServiceCommitTransactionProcedure is the fully-qualified name of the DatabaseService's
	// CommitTransaction RPC.
	DatabaseServiceCommitTransactionProcedure = "/db.v1.DatabaseService/CommitTransaction"
	// DatabaseServiceRollbackTransactionProcedure is the fully-qualified name of the DatabaseService's
	// RollbackTransaction RPC.
	DatabaseServiceRollbackTransactionProcedure = "/db.v1.DatabaseService/RollbackTransaction"
	// DatabaseServiceExecuteTransactionProcedure is the fully-qualified name of the DatabaseService's
	// ExecuteTransaction RPC.
	DatabaseServiceExecuteTransactionProcedure = "/db.v1.DatabaseService/ExecuteTransaction"
	// DatabaseServiceTypedQueryProcedure is the fully-qualified name of the DatabaseService's
	// TypedQuery RPC.
	DatabaseServiceTypedQueryProcedure = "/db.v1.DatabaseService/TypedQuery"
	// DatabaseServiceTypedQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// TypedQueryStream RPC.
	DatabaseServiceTypedQueryStreamProcedure = "/db.v1.DatabaseService/TypedQueryStream"
	// DatabaseServiceTypedTransactionQueryProcedure is the fully-qualified name of the
	// DatabaseService's TypedTransactionQuery RPC.
	DatabaseServiceTypedTransactionQueryProcedure = "/db.v1.DatabaseService/TypedTransactionQuery"
	// DatabaseServiceTypedTransactionQueryStreamProcedure is the fully-qualified name of the
	// DatabaseService's TypedTransactionQueryStream RPC.
	DatabaseServiceTypedTransactionQueryStreamProcedure = "/db.v1.DatabaseService/TypedTransactionQueryStream"
	// DatabaseServiceExplainProcedure is the fully-qualified name of the DatabaseService's Explain RPC.
	DatabaseServiceExplainProcedure = "/db.v1.DatabaseService/Explain"
	// DatabaseServiceTypedExplainProcedure is the fully-qualified name of the DatabaseService's
	// TypedExplain RPC.
	DatabaseServiceTypedExplainProcedure = "/db.v1.DatabaseService/TypedExplain"
	// DatabaseServiceListTablesProcedure is the fully-qualified name of the DatabaseService's
	// ListTables RPC.
	DatabaseServiceListTablesProcedure = "/db.v1.DatabaseService/ListTables"
	// DatabaseServiceGetTableSchemaProcedure is the fully-qualified name of the DatabaseService's
	// GetTableSchema RPC.
	DatabaseServiceGetTableSchemaProcedure = "/db.v1.DatabaseService/GetTableSchema"
	// DatabaseServiceGetDatabaseSchemaProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseSchema RPC.
	DatabaseServiceGetDatabaseSchemaProcedure = "/db.v1.DatabaseService/GetDatabaseSchema"
	// AdminServiceCreateUserProcedure is the fully-qualified name of the AdminService's CreateUser RPC.
	AdminServiceCreateUserProcedure = "/db.v1.AdminService/CreateUser"
	// AdminServiceDeleteUserProcedure is the fully-qualified name of the AdminService's DeleteUser RPC.
	AdminServiceDeleteUserProcedure = "/db.v1.AdminService/DeleteUser"
	// AdminServiceUpdatePasswordProcedure is the fully-qualified name of the AdminService's
	// UpdatePassword RPC.
	AdminServiceUpdatePasswordProcedure = "/db.v1.AdminService/UpdatePassword"
	// AdminServiceCreateApiKeyProcedure is the fully-qualified name of the AdminService's CreateApiKey
	// RPC.
	AdminServiceCreateApiKeyProcedure = "/db.v1.AdminService/CreateApiKey"
	// AdminServiceListApiKeysProcedure is the fully-qualified name of the AdminService's ListApiKeys
	// RPC.
	AdminServiceListApiKeysProcedure = "/db.v1.AdminService/ListApiKeys"
	// AdminServiceListDatabasesProcedure is the fully-qualified name of the AdminService's
	// ListDatabases RPC.
	AdminServiceListDatabasesProcedure = "/db.v1.AdminService/ListDatabases"
	// AdminServiceLoginProcedure is the fully-qualified name of the AdminService's Login RPC.
	AdminServiceLoginProcedure = "/db.v1.AdminService/Login"
	// AdminServiceLogoutProcedure is the fully-qualified name of the AdminService's Logout RPC.
	AdminServiceLogoutProcedure = "/db.v1.AdminService/Logout"
	// AdminServiceRevokeApiKeyProcedure is the fully-qualified name of the AdminService's RevokeApiKey
	// RPC.
	AdminServiceRevokeApiKeyProcedure = "/db.v1.AdminService/RevokeApiKey"
	// AdminServiceCreateDatabaseProcedure is the fully-qualified name of the AdminService's
	// CreateDatabase RPC.
	AdminServiceCreateDatabaseProcedure = "/db.v1.AdminService/CreateDatabase"
	// AdminServiceMountDatabaseProcedure is the fully-qualified name of the AdminService's
	// MountDatabase RPC.
	AdminServiceMountDatabaseProcedure = "/db.v1.AdminService/MountDatabase"
	// AdminServiceUnMountDatabaseProcedure is the fully-qualified name of the AdminService's
	// UnMountDatabase RPC.
	AdminServiceUnMountDatabaseProcedure = "/db.v1.AdminService/UnMountDatabase"
	// AdminServiceDeleteDatabaseProcedure is the fully-qualified name of the AdminService's
	// DeleteDatabase RPC.
	AdminServiceDeleteDatabaseProcedure = "/db.v1.AdminService/DeleteDatabase"
)

// DatabaseServiceClient is a client for the db.v1.DatabaseService service.
type DatabaseServiceClient interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for
	// this RPC. For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse]
	// *
	// Starts a new transaction context on the server and returns a
	// 'transaction_id'. The server holds the connection open in memory until
	// Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// The server will stream the results back to the client.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Manages a savepoint (nested transaction) within an existing transaction ID.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Commits the transaction associated with the ID and releases server
	// resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server
	// resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
	// *
	// Executes a single stateless query and returns the entire result with
	// strongly-typed values. Eliminates the need for sparse type hints.
	TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Executes a stateless query and streams strongly-typed results.
	// Protocol: TypedHeader -> TypedBatch... -> Complete
	TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error)
	// *
	// Executes a typed query inside the context of an existing 'transaction_id'.
	TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Executes a typed query inside the context of an existing 'transaction_id'.
	// The server will stream the typed results back to the client.
	TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error)
	// *
	// Returns structured EXPLAIN QUERY PLAN output as a tree.
	// Helps developers understand index usage and optimization opportunities.
	Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Typed variant of Explain using strongly-typed parameters.
	// Returns the same structured EXPLAIN QUERY PLAN output.
	TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Returns a light listing of all tables in the database.
	// Useful for UI dropdowns and quick navigation.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// *
	// Returns detailed schema for a single table.
	// Includes columns, indexes, foreign keys, and triggers.
	GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error)
	// *
	// Returns the full database schema for exports/migrations.
	// Aggregates all tables with their complete schema information.
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error)
}

// NewDatabaseServiceClient constructs a client for the db.v1.DatabaseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		query: connect.NewClient[v1.QueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		queryStream: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
			connect.WithClientOptions(opts...),
		),
		transaction: connect.NewClient[v1.TransactionRequest, v1.TransactionResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
			connect.WithClientOptions(opts...),
		),
		beginTransaction: connect.NewClient[v1.BeginTransactionRequest, v1.BeginTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceBeginTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
			connect.WithClientOptions(opts...),
		),
		transactionQuery: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		transactionQueryStream: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
			connect.WithClientOptions(opts...),
		),
		transactionSavepoint: connect.NewClient[v1.TransactionSavepointRequest, v1.SavepointResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionSavepointProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
			connect.WithClientOptions(opts...),
		),
		commitTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceCommitTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
			connect.WithClientOptions(opts...),
		),
		rollbackTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceRollbackTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
			connect.WithClientOptions(opts...),
		),
		executeTransaction: connect.NewClient[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceExecuteTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
			connect.WithClientOptions(opts...),
		),
		typedQuery: connect.NewClient[v1.TypedQueryRequest, v1.TypedQueryResult](
			httpClient,
			baseURL+DatabaseServiceTypedQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedQuery")),
			connect.WithClientOptions(opts...),
		),
		typedQueryStream: connect.NewClient[v1.TypedQueryRequest, v1.TypedQueryResponse](
			httpClient,
			baseURL+DatabaseServiceTypedQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedQueryStream")),
			connect.WithClientOptions(opts...),
		),
		typedTransactionQuery: connect.NewClient[v1.TypedTransactionQueryRequest, v1.TypedQueryResult](
			httpClient,
			baseURL+DatabaseServiceTypedTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		typedTransactionQueryStream: connect.NewClient[v1.TypedTransactionQueryRequest, v1.TypedQueryResponse](
			httpClient,
			baseURL+DatabaseServiceTypedTransactionQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQueryStream")),
			connect.WithClientOptions(opts...),
		),
		explain: connect.NewClient[v1.QueryRequest, v1.ExplainResponse](
			httpClient,
			baseURL+DatabaseServiceExplainProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Explain")),
			connect.WithClientOptions(opts...),
		),
		typedExplain: connect.NewClient[v1.TypedQueryRequest, v1.ExplainResponse](
			httpClient,
			baseURL+DatabaseServiceTypedExplainProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedExplain")),
			connect.WithClientOptions(opts...),
		),
		listTables: connect.NewClient[v1.ListTablesRequest, v1.ListTablesResponse](
			httpClient,
			baseURL+DatabaseServiceListTablesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
			connect.WithClientOptions(opts...),
		),
		getTableSchema: connect.NewClient[v1.GetTableSchemaRequest, v1.TableSchema](
			httpClient,
			baseURL+DatabaseServiceGetTableSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTableSchema")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseSchema: connect.NewClient[v1.GetDatabaseSchemaRequest, v1.DatabaseSchema](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	query                       *connect.Client[v1.QueryRequest, v1.QueryResult]
	queryStream                 *connect.Client[v1.QueryRequest, v1.QueryResponse]
	transaction                 *connect.Client[v1.TransactionRequest, v1.TransactionResponse]
	beginTransaction            *connect.Client[v1.BeginTransactionRequest, v1.BeginTransactionResponse]
	transactionQuery            *connect.Client[v1.TransactionQueryRequest, v1.QueryResult]
	transactionQueryStream      *connect.Client[v1.TransactionQueryRequest, v1.QueryResponse]
	transactionSavepoint        *connect.Client[v1.TransactionSavepointRequest, v1.SavepointResponse]
	commitTransaction           *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	rollbackTransaction         *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	executeTransaction          *connect.Client[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse]
	typedQuery                  *connect.Client[v1.TypedQueryRequest, v1.TypedQueryResult]
	typedQueryStream            *connect.Client[v1.TypedQueryRequest, v1.TypedQueryResponse]
	typedTransactionQuery       *connect.Client[v1.TypedTransactionQueryRequest, v1.TypedQueryResult]
	typedTransactionQueryStream *connect.Client[v1.TypedTransactionQueryRequest, v1.TypedQueryResponse]
	explain                     *connect.Client[v1.QueryRequest, v1.ExplainResponse]
	typedExplain                *connect.Client[v1.TypedQueryRequest, v1.ExplainResponse]
	listTables                  *connect.Client[v1.ListTablesRequest, v1.ListTablesResponse]
	getTableSchema              *connect.Client[v1.GetTableSchemaRequest, v1.TableSchema]
	getDatabaseSchema           *connect.Client[v1.GetDatabaseSchemaRequest, v1.DatabaseSchema]
}

// Query calls db.v1.DatabaseService.Query.
func (c *databaseServiceClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.query.CallUnary(ctx, req)
}

// QueryStream calls db.v1.DatabaseService.QueryStream.
func (c *databaseServiceClient) QueryStream(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.queryStream.CallServerStream(ctx, req)
}

// Transaction calls db.v1.DatabaseService.Transaction.
func (c *databaseServiceClient) Transaction(ctx context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse] {
	return c.transaction.CallBidiStream(ctx)
}

// BeginTransaction calls db.v1.DatabaseService.BeginTransaction.
func (c *databaseServiceClient) BeginTransaction(ctx context.Context, req *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return c.beginTransaction.CallUnary(ctx, req)
}

// TransactionQuery calls db.v1.DatabaseService.TransactionQuery.
func (c *databaseServiceClient) TransactionQuery(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.transactionQuery.CallUnary(ctx, req)
}

// TransactionQueryStream calls db.v1.DatabaseService.TransactionQueryStream.
func (c *databaseServiceClient) TransactionQueryStream(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.transactionQueryStream.CallServerStream(ctx, req)
}

// TransactionSavepoint calls db.v1.DatabaseService.TransactionSavepoint.
func (c *databaseServiceClient) TransactionSavepoint(ctx context.Context, req *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return c.transactionSavepoint.CallUnary(ctx, req)
}

// CommitTransaction calls db.v1.DatabaseService.CommitTransaction.
func (c *databaseServiceClient) CommitTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.commitTransaction.CallUnary(ctx, req)
}

// RollbackTransaction calls db.v1.DatabaseService.RollbackTransaction.
func (c *databaseServiceClient) RollbackTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.rollbackTransaction.CallUnary(ctx, req)
}

// ExecuteTransaction calls db.v1.DatabaseService.ExecuteTransaction.
func (c *databaseServiceClient) ExecuteTransaction(ctx context.Context, req *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return c.executeTransaction.CallUnary(ctx, req)
}

// TypedQuery calls db.v1.DatabaseService.TypedQuery.
func (c *databaseServiceClient) TypedQuery(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return c.typedQuery.CallUnary(ctx, req)
}

// TypedQueryStream calls db.v1.DatabaseService.TypedQueryStream.
func (c *databaseServiceClient) TypedQueryStream(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error) {
	return c.typedQueryStream.CallServerStream(ctx, req)
}

// TypedTransactionQuery calls db.v1.DatabaseService.TypedTransactionQuery.
func (c *databaseServiceClient) TypedTransactionQuery(ctx context.Context, req *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return c.typedTransactionQuery.CallUnary(ctx, req)
}

// TypedTransactionQueryStream calls db.v1.DatabaseService.TypedTransactionQueryStream.
func (c *databaseServiceClient) TypedTransactionQueryStream(ctx context.Context, req *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error) {
	return c.typedTransactionQueryStream.CallServerStream(ctx, req)
}

// Explain calls db.v1.DatabaseService.Explain.
func (c *databaseServiceClient) Explain(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return c.explain.CallUnary(ctx, req)
}

// TypedExplain calls db.v1.DatabaseService.TypedExplain.
func (c *databaseServiceClient) TypedExplain(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return c.typedExplain.CallUnary(ctx, req)
}

// ListTables calls db.v1.DatabaseService.ListTables.
func (c *databaseServiceClient) ListTables(ctx context.Context, req *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return c.listTables.CallUnary(ctx, req)
}

// GetTableSchema calls db.v1.DatabaseService.GetTableSchema.
func (c *databaseServiceClient) GetTableSchema(ctx context.Context, req *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error) {
	return c.getTableSchema.CallUnary(ctx, req)
}

// GetDatabaseSchema calls db.v1.DatabaseService.GetDatabaseSchema.
func (c *databaseServiceClient) GetDatabaseSchema(ctx context.Context, req *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error) {
	return c.getDatabaseSchema.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the db.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for
	// this RPC. For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error
	// *
	// Starts a new transaction context on the server and returns a
	// 'transaction_id'. The server holds the connection open in memory until
	// Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// The server will stream the results back to the client.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Manages a savepoint (nested transaction) within an existing transaction ID.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Commits the transaction associated with the ID and releases server
	// resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server
	// resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
	// *
	// Executes a single stateless query and returns the entire result with
	// strongly-typed values. Eliminates the need for sparse type hints.
	TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Executes a stateless query and streams strongly-typed results.
	// Protocol: TypedHeader -> TypedBatch... -> Complete
	TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error
	// *
	// Executes a typed query inside the context of an existing 'transaction_id'.
	TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Executes a typed query inside the context of an existing 'transaction_id'.
	// The server will stream the typed results back to the client.
	TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error
	// *
	// Returns structured EXPLAIN QUERY PLAN output as a tree.
	// Helps developers understand index usage and optimization opportunities.
	Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Typed variant of Explain using strongly-typed parameters.
	// Returns the same structured EXPLAIN QUERY PLAN output.
	TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Returns a light listing of all tables in the database.
	// Useful for UI dropdowns and quick navigation.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// *
	// Returns detailed schema for a single table.
	// Includes columns, indexes, foreign keys, and triggers.
	GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error)
	// *
	// Returns the full database schema for exports/migrations.
	// Aggregates all tables with their complete schema information.
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(databaseServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceQueryStreamProcedure,
		svc.QueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionHandler := connect.NewBidiStreamHandler(
		DatabaseServiceTransactionProcedure,
		svc.Transaction,
		connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceBeginTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceBeginTransactionProcedure,
		svc.BeginTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionQueryProcedure,
		svc.TransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTransactionQueryStreamProcedure,
		svc.TransactionQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionSavepointHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionSavepointProcedure,
		svc.TransactionSavepoint,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCommitTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceCommitTransactionProcedure,
		svc.CommitTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRollbackTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceRollbackTransactionProcedure,
		svc.RollbackTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecuteTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceExecuteTransactionProcedure,
		svc.ExecuteTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedQueryProcedure,
		svc.TypedQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TypedQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTypedQueryStreamProcedure,
		svc.TypedQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TypedQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedTransactionQueryProcedure,
		svc.TypedTransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedTransactionQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTypedTransactionQueryStreamProcedure,
		svc.TypedTransactionQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExplainHandler := connect.NewUnaryHandler(
		DatabaseServiceExplainProcedure,
		svc.Explain,
		connect.WithSchema(databaseServiceMethods.ByName("Explain")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedExplainHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedExplainProcedure,
		svc.TypedExplain,
		connect.WithSchema(databaseServiceMethods.ByName("TypedExplain")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListTablesHandler := connect.NewUnaryHandler(
		DatabaseServiceListTablesProcedure,
		svc.ListTables,
		connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTableSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTableSchemaProcedure,
		svc.GetTableSchema,
		connect.WithSchema(databaseServiceMethods.ByName("GetTableSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseSchemaProcedure,
		svc.GetDatabaseSchema,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
		connect.WithHandlerOptions(opts...),
	)
	return "/db.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceQueryProcedure:
			databaseServiceQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceQueryStreamProcedure:
			databaseServiceQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionProcedure:
			databaseServiceTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceBeginTransactionProcedure:
			databaseServiceBeginTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryProcedure:
			databaseServiceTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryStreamProcedure:
			databaseServiceTransactionQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionSavepointProcedure:
			databaseServiceTransactionSavepointHandler.ServeHTTP(w, r)
		case DatabaseServiceCommitTransactionProcedure:
			databaseServiceCommitTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceRollbackTransactionProcedure:
			databaseServiceRollbackTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceExecuteTransactionProcedure:
			databaseServiceExecuteTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedQueryProcedure:
			databaseServiceTypedQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedQueryStreamProcedure:
			databaseServiceTypedQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedTransactionQueryProcedure:
			databaseServiceTypedTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedTransactionQueryStreamProcedure:
			databaseServiceTypedTransactionQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceExplainProcedure:
			databaseServiceExplainHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedExplainProcedure:
			databaseServiceTypedExplainHandler.ServeHTTP(w, r)
		case DatabaseServiceListTablesProcedure:
			databaseServiceListTablesHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTableSchemaProcedure:
			databaseServiceGetTableSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseSchemaProcedure:
			databaseServiceGetDatabaseSchemaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Query is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.QueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Transaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.BeginTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionSavepoint is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.CommitTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.RollbackTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.ExecuteTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TypedQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TypedQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TypedTransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TypedTransactionQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Explain is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TypedExplain is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.ListTables is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.GetTableSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.GetDatabaseSchema is not implemented"))
}

// AdminServiceClient is a client for the db.v1.AdminService service.
type AdminServiceClient interface {
	// *
	// Creates a new user with specific role-based access.
	// Requires admin privileges.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// Permanently removes a user from the system.
	// Existing connections for this user may be terminated.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// Rotates the password for a specific user.
	// The new password takes effect immediately for new connections.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
	// *
	// Generates a long-lived API key for a specific user.
	// The key is only returned once in the response.
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// *
	// Retrieves all active API keys for a specific user.
	// Returns metadata (name, prefix) but not the full key secrets.
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// *
	// Lists all available databases.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Authenticates a user and returns a session API key.
	// Requires Basic Auth for the initial request.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Invalidates the current session/API key.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// *
	// Revokes (deletes) a specific API key immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// *
	// Creates a new managed database.
	// The database file is created in the server's managed directory.
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	MountDatabase(context.Context, *connect.Request[v1.DatabaseConfig]) (*connect.Response[v1.MountDatabaseResponse], error)
	// *
	// Unmounts a database, removing it from the active server.
	// The file is NOT deleted.
	UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error)
	// *
	// Deletes a database securely.
	// - Managed DBs: Deleted from disk and metadata.
	// - Mounted DBs: Returns error (protects external files).
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
}

// NewAdminServiceClient constructs a client for the db.v1.AdminService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+AdminServiceCreateUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+AdminServiceDeleteUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		updatePassword: connect.NewClient[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse](
			httpClient,
			baseURL+AdminServiceUpdatePasswordProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+AdminServiceCreateApiKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+AdminServiceListApiKeysProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListApiKeys")),
			connect.WithClientOptions(opts...),
		),
		listDatabases: connect.NewClient[v1.ListDatabasesRequest, v1.ListDatabasesResponse](
			httpClient,
			baseURL+AdminServiceListDatabasesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AdminServiceLoginProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AdminServiceLogoutProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse](
			httpClient,
			baseURL+AdminServiceRevokeApiKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RevokeApiKey")),
			connect.WithClientOptions(opts...),
		),
		createDatabase: connect.NewClient[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse](
			httpClient,
			baseURL+AdminServiceCreateDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateDatabase")),
			connect.WithClientOptions(opts...),
		),
		mountDatabase: connect.NewClient[v1.DatabaseConfig, v1.MountDatabaseResponse](
			httpClient,
			baseURL+AdminServiceMountDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("MountDatabase")),
			connect.WithClientOptions(opts...),
		),
		unMountDatabase: connect.NewClient[v1.UnMountDatabaseRequest, v1.UnMountDatabaseResponse](
			httpClient,
			baseURL+AdminServiceUnMountDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UnMountDatabase")),
			connect.WithClientOptions(opts...),
		),
		deleteDatabase: connect.NewClient[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse](
			httpClient,
			baseURL+AdminServiceDeleteDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteDatabase")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	createUser      *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	deleteUser      *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	updatePassword  *connect.Client[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse]
	createApiKey    *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	listApiKeys     *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	listDatabases   *connect.Client[v1.ListDatabasesRequest, v1.ListDatabasesResponse]
	login           *connect.Client[v1.LoginRequest, v1.LoginResponse]
	logout          *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
	revokeApiKey    *connect.Client[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse]
	createDatabase  *connect.Client[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse]
	mountDatabase   *connect.Client[v1.DatabaseConfig, v1.MountDatabaseResponse]
	unMountDatabase *connect.Client[v1.UnMountDatabaseRequest, v1.UnMountDatabaseResponse]
	deleteDatabase  *connect.Client[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse]
}

// CreateUser calls db.v1.AdminService.CreateUser.
func (c *adminServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// DeleteUser calls db.v1.AdminService.DeleteUser.
func (c *adminServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// UpdatePassword calls db.v1.AdminService.UpdatePassword.
func (c *adminServiceClient) UpdatePassword(ctx context.Context, req *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return c.updatePassword.CallUnary(ctx, req)
}

// CreateApiKey calls db.v1.AdminService.CreateApiKey.
func (c *adminServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls db.v1.AdminService.ListApiKeys.
func (c *adminServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// ListDatabases calls db.v1.AdminService.ListDatabases.
func (c *adminServiceClient) ListDatabases(ctx context.Context, req *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return c.listDatabases.CallUnary(ctx, req)
}

// Login calls db.v1.AdminService.Login.
func (c *adminServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls db.v1.AdminService.Logout.
func (c *adminServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// RevokeApiKey calls db.v1.AdminService.RevokeApiKey.
func (c *adminServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// CreateDatabase calls db.v1.AdminService.CreateDatabase.
func (c *adminServiceClient) CreateDatabase(ctx context.Context, req *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return c.createDatabase.CallUnary(ctx, req)
}

// MountDatabase calls db.v1.AdminService.MountDatabase.
func (c *adminServiceClient) MountDatabase(ctx context.Context, req *connect.Request[v1.DatabaseConfig]) (*connect.Response[v1.MountDatabaseResponse], error) {
	return c.mountDatabase.CallUnary(ctx, req)
}

// UnMountDatabase calls db.v1.AdminService.UnMountDatabase.
func (c *adminServiceClient) UnMountDatabase(ctx context.Context, req *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error) {
	return c.unMountDatabase.CallUnary(ctx, req)
}

// DeleteDatabase calls db.v1.AdminService.DeleteDatabase.
func (c *adminServiceClient) DeleteDatabase(ctx context.Context, req *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return c.deleteDatabase.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the db.v1.AdminService service.
type AdminServiceHandler interface {
	// *
	// Creates a new user with specific role-based access.
	// Requires admin privileges.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// Permanently removes a user from the system.
	// Existing connections for this user may be terminated.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// Rotates the password for a specific user.
	// The new password takes effect immediately for new connections.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
	// *
	// Generates a long-lived API key for a specific user.
	// The key is only returned once in the response.
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// *
	// Retrieves all active API keys for a specific user.
	// Returns metadata (name, prefix) but not the full key secrets.
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// *
	// Lists all available databases.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Authenticates a user and returns a session API key.
	// Requires Basic Auth for the initial request.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Invalidates the current session/API key.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// *
	// Revokes (deletes) a specific API key immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// *
	// Creates a new managed database.
	// The database file is created in the server's managed directory.
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	MountDatabase(context.Context, *connect.Request[v1.DatabaseConfig]) (*connect.Response[v1.MountDatabaseResponse], error)
	// *
	// Unmounts a database, removing it from the active server.
	// The file is NOT deleted.
	UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error)
	// *
	// Deletes a database securely.
	// - Managed DBs: Deleted from disk and metadata.
	// - Mounted DBs: Returns error (protects external files).
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("AdminService").Methods()
	adminServiceCreateUserHandler := connect.NewUnaryHandler(
		AdminServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUserHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdatePasswordHandler := connect.NewUnaryHandler(
		AdminServiceUpdatePasswordProcedure,
		svc.UpdatePassword,
		connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		AdminServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(adminServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListApiKeysHandler := connect.NewUnaryHandler(
		AdminServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(adminServiceMethods.ByName("ListApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListDatabasesHandler := connect.NewUnaryHandler(
		AdminServiceListDatabasesProcedure,
		svc.ListDatabases,
		connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceLoginHandler := connect.NewUnaryHandler(
		AdminServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(adminServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceLogoutHandler := connect.NewUnaryHandler(
		AdminServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(adminServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		AdminServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(adminServiceMethods.ByName("RevokeApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceCreateDatabaseProcedure,
		svc.CreateDatabase,
		connect.WithSchema(adminServiceMethods.ByName("CreateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceMountDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceMountDatabaseProcedure,
		svc.MountDatabase,
		connect.WithSchema(adminServiceMethods.ByName("MountDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUnMountDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceUnMountDatabaseProcedure,
		svc.UnMountDatabase,
		connect.WithSchema(adminServiceMethods.ByName("UnMountDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceDeleteDatabaseProcedure,
		svc.DeleteDatabase,
		connect.WithSchema(adminServiceMethods.ByName("DeleteDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	return "/db.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceCreateUserProcedure:
			adminServiceCreateUserHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUserProcedure:
			adminServiceDeleteUserHandler.ServeHTTP(w, r)
		case AdminServiceUpdatePasswordProcedure:
			adminServiceUpdatePasswordHandler.ServeHTTP(w, r)
		case AdminServiceCreateApiKeyProcedure:
			adminServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case AdminServiceListApiKeysProcedure:
			adminServiceListApiKeysHandler.ServeHTTP(w, r)
		case AdminServiceListDatabasesProcedure:
			adminServiceListDatabasesHandler.ServeHTTP(w, r)
		case AdminServiceLoginProcedure:
			adminServiceLoginHandler.ServeHTTP(w, r)
		case AdminServiceLogoutProcedure:
			adminServiceLogoutHandler.ServeHTTP(w, r)
		case AdminServiceRevokeApiKeyProcedure:
			adminServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		case AdminServiceCreateDatabaseProcedure:
			adminServiceCreateDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceMountDatabaseProcedure:
			adminServiceMountDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceUnMountDatabaseProcedure:
			adminServiceUnMountDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceDeleteDatabaseProcedure:
			adminServiceDeleteDatabaseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.CreateUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.DeleteUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.UpdatePassword is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.CreateApiKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.ListApiKeys is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.ListDatabases is not implemented"))
}

func (UnimplementedAdminServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.Login is not implemented"))
}

func (UnimplementedAdminServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.Logout is not implemented"))
}

func (UnimplementedAdminServiceHandler) RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.RevokeApiKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.CreateDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) MountDatabase(context.Context, *connect.Request[v1.DatabaseConfig]) (*connect.Response[v1.MountDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.MountDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.UnMountDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.DeleteDatabase is not implemented"))
}
