//*
// @file db/v1/database.proto
// @description The definitive gRPC contract for the sqlite-server service.
//
// ARCHITECTURAL DESIGN:
//
// 1. DUAL TRANSACTION MODELS:
//    - Streaming (Bidirectional): Best for short, interactive sessions where
// the connection lifespan equals the transaction lifespan. Automatic rollback
// on disconnect.
//    - Unary (ID-Based): Best for stateless HTTP clients or long-running
// workflows where holding a TCP connection open is brittle. Requires manual
// 'Begin'/'Commit' and relies on server-side Timeouts (TTL) to clean up
// "Zombie" transactions.
//
// 2. TYPE SAFETY (SPARSE HINTS):
//    Since JSON/Protobuf lacks native support for some SQLite types (like BLOBs
// or large Integers), we use a "Hint" system. The client sends data as standard
// JSON types but provides a mapping (e.g., "param 0 is a BLOB") so the server
// knows to decode Base64 before hitting the DB.
//
// 3. ERROR FIDELITY:
//    We map native C SQLite result codes to a Proto Enum (`SqliteCode`). This
// allows clients to programmatically react to specific errors (e.g., retrying
// on SQLITE_BUSY) without parsing error string messages.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: db/v1/db_service.proto

package dbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sqlite-server/internal/protos/db/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "db.v1.DatabaseService"
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "db.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceQueryProcedure is the fully-qualified name of the DatabaseService's Query RPC.
	DatabaseServiceQueryProcedure = "/db.v1.DatabaseService/Query"
	// DatabaseServiceQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// QueryStream RPC.
	DatabaseServiceQueryStreamProcedure = "/db.v1.DatabaseService/QueryStream"
	// DatabaseServiceTransactionProcedure is the fully-qualified name of the DatabaseService's
	// Transaction RPC.
	DatabaseServiceTransactionProcedure = "/db.v1.DatabaseService/Transaction"
	// DatabaseServiceBeginTransactionProcedure is the fully-qualified name of the DatabaseService's
	// BeginTransaction RPC.
	DatabaseServiceBeginTransactionProcedure = "/db.v1.DatabaseService/BeginTransaction"
	// DatabaseServiceTransactionQueryProcedure is the fully-qualified name of the DatabaseService's
	// TransactionQuery RPC.
	DatabaseServiceTransactionQueryProcedure = "/db.v1.DatabaseService/TransactionQuery"
	// DatabaseServiceTransactionQueryStreamProcedure is the fully-qualified name of the
	// DatabaseService's TransactionQueryStream RPC.
	DatabaseServiceTransactionQueryStreamProcedure = "/db.v1.DatabaseService/TransactionQueryStream"
	// DatabaseServiceTransactionSavepointProcedure is the fully-qualified name of the DatabaseService's
	// TransactionSavepoint RPC.
	DatabaseServiceTransactionSavepointProcedure = "/db.v1.DatabaseService/TransactionSavepoint"
	// DatabaseServiceCommitTransactionProcedure is the fully-qualified name of the DatabaseService's
	// CommitTransaction RPC.
	DatabaseServiceCommitTransactionProcedure = "/db.v1.DatabaseService/CommitTransaction"
	// DatabaseServiceRollbackTransactionProcedure is the fully-qualified name of the DatabaseService's
	// RollbackTransaction RPC.
	DatabaseServiceRollbackTransactionProcedure = "/db.v1.DatabaseService/RollbackTransaction"
	// DatabaseServiceExecuteTransactionProcedure is the fully-qualified name of the DatabaseService's
	// ExecuteTransaction RPC.
	DatabaseServiceExecuteTransactionProcedure = "/db.v1.DatabaseService/ExecuteTransaction"
	// AdminServiceCreateUserProcedure is the fully-qualified name of the AdminService's CreateUser RPC.
	AdminServiceCreateUserProcedure = "/db.v1.AdminService/CreateUser"
	// AdminServiceDeleteUserProcedure is the fully-qualified name of the AdminService's DeleteUser RPC.
	AdminServiceDeleteUserProcedure = "/db.v1.AdminService/DeleteUser"
	// AdminServiceUpdatePasswordProcedure is the fully-qualified name of the AdminService's
	// UpdatePassword RPC.
	AdminServiceUpdatePasswordProcedure = "/db.v1.AdminService/UpdatePassword"
	// AdminServiceCreateApiKeyProcedure is the fully-qualified name of the AdminService's CreateApiKey
	// RPC.
	AdminServiceCreateApiKeyProcedure = "/db.v1.AdminService/CreateApiKey"
	// AdminServiceListApiKeysProcedure is the fully-qualified name of the AdminService's ListApiKeys
	// RPC.
	AdminServiceListApiKeysProcedure = "/db.v1.AdminService/ListApiKeys"
	// AdminServiceListDatabasesProcedure is the fully-qualified name of the AdminService's
	// ListDatabases RPC.
	AdminServiceListDatabasesProcedure = "/db.v1.AdminService/ListDatabases"
	// AdminServiceLoginProcedure is the fully-qualified name of the AdminService's Login RPC.
	AdminServiceLoginProcedure = "/db.v1.AdminService/Login"
	// AdminServiceRevokeApiKeyProcedure is the fully-qualified name of the AdminService's RevokeApiKey
	// RPC.
	AdminServiceRevokeApiKeyProcedure = "/db.v1.AdminService/RevokeApiKey"
	// AdminServiceBackupDatabaseProcedure is the fully-qualified name of the AdminService's
	// BackupDatabase RPC.
	AdminServiceBackupDatabaseProcedure = "/db.v1.AdminService/BackupDatabase"
	// AdminServiceRestoreDatabaseProcedure is the fully-qualified name of the AdminService's
	// RestoreDatabase RPC.
	AdminServiceRestoreDatabaseProcedure = "/db.v1.AdminService/RestoreDatabase"
)

// DatabaseServiceClient is a client for the db.v1.DatabaseService service.
type DatabaseServiceClient interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for
	// this RPC. For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse]
	// *
	// Starts a new transaction context on the server and returns a
	// 'transaction_id'. The server holds the connection open in memory until
	// Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// The server will stream the results back to the client.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Manages a savepoint (nested transaction) within an existing transaction ID.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Commits the transaction associated with the ID and releases server
	// resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server
	// resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
}

// NewDatabaseServiceClient constructs a client for the db.v1.DatabaseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		query: connect.NewClient[v1.QueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		queryStream: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
			connect.WithClientOptions(opts...),
		),
		transaction: connect.NewClient[v1.TransactionRequest, v1.TransactionResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
			connect.WithClientOptions(opts...),
		),
		beginTransaction: connect.NewClient[v1.BeginTransactionRequest, v1.BeginTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceBeginTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
			connect.WithClientOptions(opts...),
		),
		transactionQuery: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		transactionQueryStream: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
			connect.WithClientOptions(opts...),
		),
		transactionSavepoint: connect.NewClient[v1.TransactionSavepointRequest, v1.SavepointResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionSavepointProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
			connect.WithClientOptions(opts...),
		),
		commitTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceCommitTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
			connect.WithClientOptions(opts...),
		),
		rollbackTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceRollbackTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
			connect.WithClientOptions(opts...),
		),
		executeTransaction: connect.NewClient[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceExecuteTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	query                  *connect.Client[v1.QueryRequest, v1.QueryResult]
	queryStream            *connect.Client[v1.QueryRequest, v1.QueryResponse]
	transaction            *connect.Client[v1.TransactionRequest, v1.TransactionResponse]
	beginTransaction       *connect.Client[v1.BeginTransactionRequest, v1.BeginTransactionResponse]
	transactionQuery       *connect.Client[v1.TransactionQueryRequest, v1.QueryResult]
	transactionQueryStream *connect.Client[v1.TransactionQueryRequest, v1.QueryResponse]
	transactionSavepoint   *connect.Client[v1.TransactionSavepointRequest, v1.SavepointResponse]
	commitTransaction      *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	rollbackTransaction    *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	executeTransaction     *connect.Client[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse]
}

// Query calls db.v1.DatabaseService.Query.
func (c *databaseServiceClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.query.CallUnary(ctx, req)
}

// QueryStream calls db.v1.DatabaseService.QueryStream.
func (c *databaseServiceClient) QueryStream(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.queryStream.CallServerStream(ctx, req)
}

// Transaction calls db.v1.DatabaseService.Transaction.
func (c *databaseServiceClient) Transaction(ctx context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse] {
	return c.transaction.CallBidiStream(ctx)
}

// BeginTransaction calls db.v1.DatabaseService.BeginTransaction.
func (c *databaseServiceClient) BeginTransaction(ctx context.Context, req *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return c.beginTransaction.CallUnary(ctx, req)
}

// TransactionQuery calls db.v1.DatabaseService.TransactionQuery.
func (c *databaseServiceClient) TransactionQuery(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.transactionQuery.CallUnary(ctx, req)
}

// TransactionQueryStream calls db.v1.DatabaseService.TransactionQueryStream.
func (c *databaseServiceClient) TransactionQueryStream(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.transactionQueryStream.CallServerStream(ctx, req)
}

// TransactionSavepoint calls db.v1.DatabaseService.TransactionSavepoint.
func (c *databaseServiceClient) TransactionSavepoint(ctx context.Context, req *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return c.transactionSavepoint.CallUnary(ctx, req)
}

// CommitTransaction calls db.v1.DatabaseService.CommitTransaction.
func (c *databaseServiceClient) CommitTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.commitTransaction.CallUnary(ctx, req)
}

// RollbackTransaction calls db.v1.DatabaseService.RollbackTransaction.
func (c *databaseServiceClient) RollbackTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.rollbackTransaction.CallUnary(ctx, req)
}

// ExecuteTransaction calls db.v1.DatabaseService.ExecuteTransaction.
func (c *databaseServiceClient) ExecuteTransaction(ctx context.Context, req *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return c.executeTransaction.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the db.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	// *
	// Executes a single stateless query and returns the entire result.
	// Best for point-lookups (SELECT ... WHERE id=?).
	//
	// WARNING: The server enforces a hard limit on row count (e.g., 1000) for
	// this RPC. For larger datasets, use `QueryStream`.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a stateless query and streams results.
	// Safe for large exports or reporting queries.
	// Protocol: Header -> Batch... -> Batch... -> Complete
	QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Opens a stateful bidirectional stream for transactions.
	//
	// Flow:
	// 1. Client sends `BeginRequest`
	// 2. Client sends multiple `TransactionalQueryRequest`
	// 3. Client sends `Commit` or `Rollback`
	Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error
	// *
	// Starts a new transaction context on the server and returns a
	// 'transaction_id'. The server holds the connection open in memory until
	// Commit, Rollback, or Timeout.
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Executes a query inside the context of an existing 'transaction_id'.
	// The server will stream the results back to the client.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Manages a savepoint (nested transaction) within an existing transaction ID.
	// If the ID is invalid or timed out, returns NOT_FOUND.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Commits the transaction associated with the ID and releases server
	// resources.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Rolls back the transaction associated with the ID and releases server
	// resources.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Executes a predefined script of commands atomically.
	// Useful for migrations or testing where interactivity is not required.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(databaseServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceQueryStreamProcedure,
		svc.QueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionHandler := connect.NewBidiStreamHandler(
		DatabaseServiceTransactionProcedure,
		svc.Transaction,
		connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceBeginTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceBeginTransactionProcedure,
		svc.BeginTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionQueryProcedure,
		svc.TransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTransactionQueryStreamProcedure,
		svc.TransactionQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionSavepointHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionSavepointProcedure,
		svc.TransactionSavepoint,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCommitTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceCommitTransactionProcedure,
		svc.CommitTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRollbackTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceRollbackTransactionProcedure,
		svc.RollbackTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecuteTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceExecuteTransactionProcedure,
		svc.ExecuteTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/db.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceQueryProcedure:
			databaseServiceQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceQueryStreamProcedure:
			databaseServiceQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionProcedure:
			databaseServiceTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceBeginTransactionProcedure:
			databaseServiceBeginTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryProcedure:
			databaseServiceTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryStreamProcedure:
			databaseServiceTransactionQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionSavepointProcedure:
			databaseServiceTransactionSavepointHandler.ServeHTTP(w, r)
		case DatabaseServiceCommitTransactionProcedure:
			databaseServiceCommitTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceRollbackTransactionProcedure:
			databaseServiceRollbackTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceExecuteTransactionProcedure:
			databaseServiceExecuteTransactionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Query is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.QueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.Transaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.BeginTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.TransactionSavepoint is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.CommitTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.RollbackTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.DatabaseService.ExecuteTransaction is not implemented"))
}

// AdminServiceClient is a client for the db.v1.AdminService service.
type AdminServiceClient interface {
	// *
	// Creates a new user with specific role-based access.
	// Requires admin privileges.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// Permanently removes a user from the system.
	// Existing connections for this user may be terminated.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// Rotates the password for a specific user.
	// The new password takes effect immediately for new connections.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
	// *
	// Generates a long-lived API key for a specific user.
	// The key is only returned once in the response.
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// *
	// Retrieves all active API keys for a specific user.
	// Returns metadata (name, prefix) but not the full key secrets.
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// *
	// Lists all available databases.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Authenticates a user and returns a session API key.
	// Requires Basic Auth for the initial request.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Revokes (deletes) a specific API key immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// *
	// Streams a binary backup of the specified database file.
	// The stream delivers the file in 4MB chunks.
	BackupDatabase(context.Context, *connect.Request[v1.BackupDatabaseRequest]) (*connect.ServerStreamForClient[v1.BackupDatabaseResponse], error)
	// *
	// Restores a database from a backup stream.
	// This overwrites the existing database file.
	// Protocol: [Metadata] -> [Chunk] -> [Chunk]...
	RestoreDatabase(context.Context) *connect.ClientStreamForClient[v1.RestoreDatabaseRequest, v1.RestoreDatabaseResponse]
}

// NewAdminServiceClient constructs a client for the db.v1.AdminService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+AdminServiceCreateUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+AdminServiceDeleteUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		updatePassword: connect.NewClient[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse](
			httpClient,
			baseURL+AdminServiceUpdatePasswordProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+AdminServiceCreateApiKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+AdminServiceListApiKeysProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListApiKeys")),
			connect.WithClientOptions(opts...),
		),
		listDatabases: connect.NewClient[v1.ListDatabasesRequest, v1.ListDatabasesResponse](
			httpClient,
			baseURL+AdminServiceListDatabasesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AdminServiceLoginProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse](
			httpClient,
			baseURL+AdminServiceRevokeApiKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RevokeApiKey")),
			connect.WithClientOptions(opts...),
		),
		backupDatabase: connect.NewClient[v1.BackupDatabaseRequest, v1.BackupDatabaseResponse](
			httpClient,
			baseURL+AdminServiceBackupDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BackupDatabase")),
			connect.WithClientOptions(opts...),
		),
		restoreDatabase: connect.NewClient[v1.RestoreDatabaseRequest, v1.RestoreDatabaseResponse](
			httpClient,
			baseURL+AdminServiceRestoreDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RestoreDatabase")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	createUser      *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	deleteUser      *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	updatePassword  *connect.Client[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse]
	createApiKey    *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	listApiKeys     *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	listDatabases   *connect.Client[v1.ListDatabasesRequest, v1.ListDatabasesResponse]
	login           *connect.Client[v1.LoginRequest, v1.LoginResponse]
	revokeApiKey    *connect.Client[v1.RevokeApiKeyRequest, v1.RevokeApiKeyResponse]
	backupDatabase  *connect.Client[v1.BackupDatabaseRequest, v1.BackupDatabaseResponse]
	restoreDatabase *connect.Client[v1.RestoreDatabaseRequest, v1.RestoreDatabaseResponse]
}

// CreateUser calls db.v1.AdminService.CreateUser.
func (c *adminServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// DeleteUser calls db.v1.AdminService.DeleteUser.
func (c *adminServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// UpdatePassword calls db.v1.AdminService.UpdatePassword.
func (c *adminServiceClient) UpdatePassword(ctx context.Context, req *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return c.updatePassword.CallUnary(ctx, req)
}

// CreateApiKey calls db.v1.AdminService.CreateApiKey.
func (c *adminServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls db.v1.AdminService.ListApiKeys.
func (c *adminServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// ListDatabases calls db.v1.AdminService.ListDatabases.
func (c *adminServiceClient) ListDatabases(ctx context.Context, req *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return c.listDatabases.CallUnary(ctx, req)
}

// Login calls db.v1.AdminService.Login.
func (c *adminServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// RevokeApiKey calls db.v1.AdminService.RevokeApiKey.
func (c *adminServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// BackupDatabase calls db.v1.AdminService.BackupDatabase.
func (c *adminServiceClient) BackupDatabase(ctx context.Context, req *connect.Request[v1.BackupDatabaseRequest]) (*connect.ServerStreamForClient[v1.BackupDatabaseResponse], error) {
	return c.backupDatabase.CallServerStream(ctx, req)
}

// RestoreDatabase calls db.v1.AdminService.RestoreDatabase.
func (c *adminServiceClient) RestoreDatabase(ctx context.Context) *connect.ClientStreamForClient[v1.RestoreDatabaseRequest, v1.RestoreDatabaseResponse] {
	return c.restoreDatabase.CallClientStream(ctx)
}

// AdminServiceHandler is an implementation of the db.v1.AdminService service.
type AdminServiceHandler interface {
	// *
	// Creates a new user with specific role-based access.
	// Requires admin privileges.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// Permanently removes a user from the system.
	// Existing connections for this user may be terminated.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// Rotates the password for a specific user.
	// The new password takes effect immediately for new connections.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
	// *
	// Generates a long-lived API key for a specific user.
	// The key is only returned once in the response.
	CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error)
	// *
	// Retrieves all active API keys for a specific user.
	// Returns metadata (name, prefix) but not the full key secrets.
	ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error)
	// *
	// Lists all available databases.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Authenticates a user and returns a session API key.
	// Requires Basic Auth for the initial request.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Revokes (deletes) a specific API key immediately.
	RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error)
	// *
	// Streams a binary backup of the specified database file.
	// The stream delivers the file in 4MB chunks.
	BackupDatabase(context.Context, *connect.Request[v1.BackupDatabaseRequest], *connect.ServerStream[v1.BackupDatabaseResponse]) error
	// *
	// Restores a database from a backup stream.
	// This overwrites the existing database file.
	// Protocol: [Metadata] -> [Chunk] -> [Chunk]...
	RestoreDatabase(context.Context, *connect.ClientStream[v1.RestoreDatabaseRequest]) (*connect.Response[v1.RestoreDatabaseResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_db_v1_db_service_proto.Services().ByName("AdminService").Methods()
	adminServiceCreateUserHandler := connect.NewUnaryHandler(
		AdminServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUserHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdatePasswordHandler := connect.NewUnaryHandler(
		AdminServiceUpdatePasswordProcedure,
		svc.UpdatePassword,
		connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		AdminServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(adminServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListApiKeysHandler := connect.NewUnaryHandler(
		AdminServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(adminServiceMethods.ByName("ListApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListDatabasesHandler := connect.NewUnaryHandler(
		AdminServiceListDatabasesProcedure,
		svc.ListDatabases,
		connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceLoginHandler := connect.NewUnaryHandler(
		AdminServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(adminServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		AdminServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(adminServiceMethods.ByName("RevokeApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBackupDatabaseHandler := connect.NewServerStreamHandler(
		AdminServiceBackupDatabaseProcedure,
		svc.BackupDatabase,
		connect.WithSchema(adminServiceMethods.ByName("BackupDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRestoreDatabaseHandler := connect.NewClientStreamHandler(
		AdminServiceRestoreDatabaseProcedure,
		svc.RestoreDatabase,
		connect.WithSchema(adminServiceMethods.ByName("RestoreDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	return "/db.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceCreateUserProcedure:
			adminServiceCreateUserHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUserProcedure:
			adminServiceDeleteUserHandler.ServeHTTP(w, r)
		case AdminServiceUpdatePasswordProcedure:
			adminServiceUpdatePasswordHandler.ServeHTTP(w, r)
		case AdminServiceCreateApiKeyProcedure:
			adminServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case AdminServiceListApiKeysProcedure:
			adminServiceListApiKeysHandler.ServeHTTP(w, r)
		case AdminServiceListDatabasesProcedure:
			adminServiceListDatabasesHandler.ServeHTTP(w, r)
		case AdminServiceLoginProcedure:
			adminServiceLoginHandler.ServeHTTP(w, r)
		case AdminServiceRevokeApiKeyProcedure:
			adminServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		case AdminServiceBackupDatabaseProcedure:
			adminServiceBackupDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceRestoreDatabaseProcedure:
			adminServiceRestoreDatabaseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.CreateUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.DeleteUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.UpdatePassword is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateApiKey(context.Context, *connect.Request[v1.CreateApiKeyRequest]) (*connect.Response[v1.CreateApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.CreateApiKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListApiKeys(context.Context, *connect.Request[v1.ListApiKeysRequest]) (*connect.Response[v1.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.ListApiKeys is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.ListDatabases is not implemented"))
}

func (UnimplementedAdminServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.Login is not implemented"))
}

func (UnimplementedAdminServiceHandler) RevokeApiKey(context.Context, *connect.Request[v1.RevokeApiKeyRequest]) (*connect.Response[v1.RevokeApiKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.RevokeApiKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) BackupDatabase(context.Context, *connect.Request[v1.BackupDatabaseRequest], *connect.ServerStream[v1.BackupDatabaseResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.BackupDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) RestoreDatabase(context.Context, *connect.ClientStream[v1.RestoreDatabaseRequest]) (*connect.Response[v1.RestoreDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("db.v1.AdminService.RestoreDatabase is not implemented"))
}
