// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sqlrpc/v1/admin_service.proto

package sqlrpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sqlite-server/internal/protos/sqlrpc/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "sqlrpc.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceListUsersProcedure is the fully-qualified name of the AdminService's ListUsers RPC.
	AdminServiceListUsersProcedure = "/sqlrpc.v1.AdminService/ListUsers"
	// AdminServiceCreateUserProcedure is the fully-qualified name of the AdminService's CreateUser RPC.
	AdminServiceCreateUserProcedure = "/sqlrpc.v1.AdminService/CreateUser"
	// AdminServiceUpdateUserRoleProcedure is the fully-qualified name of the AdminService's
	// UpdateUserRole RPC.
	AdminServiceUpdateUserRoleProcedure = "/sqlrpc.v1.AdminService/UpdateUserRole"
	// AdminServiceDeleteUserProcedure is the fully-qualified name of the AdminService's DeleteUser RPC.
	AdminServiceDeleteUserProcedure = "/sqlrpc.v1.AdminService/DeleteUser"
	// AdminServiceListAPIKeysProcedure is the fully-qualified name of the AdminService's ListAPIKeys
	// RPC.
	AdminServiceListAPIKeysProcedure = "/sqlrpc.v1.AdminService/ListAPIKeys"
	// AdminServiceCreateAPIKeyProcedure is the fully-qualified name of the AdminService's CreateAPIKey
	// RPC.
	AdminServiceCreateAPIKeyProcedure = "/sqlrpc.v1.AdminService/CreateAPIKey"
	// AdminServiceDeleteAPIKeyProcedure is the fully-qualified name of the AdminService's DeleteAPIKey
	// RPC.
	AdminServiceDeleteAPIKeyProcedure = "/sqlrpc.v1.AdminService/DeleteAPIKey"
	// AdminServiceListDatabasesProcedure is the fully-qualified name of the AdminService's
	// ListDatabases RPC.
	AdminServiceListDatabasesProcedure = "/sqlrpc.v1.AdminService/ListDatabases"
	// AdminServiceCreateDatabaseProcedure is the fully-qualified name of the AdminService's
	// CreateDatabase RPC.
	AdminServiceCreateDatabaseProcedure = "/sqlrpc.v1.AdminService/CreateDatabase"
	// AdminServiceUpdateDatabaseProcedure is the fully-qualified name of the AdminService's
	// UpdateDatabase RPC.
	AdminServiceUpdateDatabaseProcedure = "/sqlrpc.v1.AdminService/UpdateDatabase"
	// AdminServiceDeleteDatabaseProcedure is the fully-qualified name of the AdminService's
	// DeleteDatabase RPC.
	AdminServiceDeleteDatabaseProcedure = "/sqlrpc.v1.AdminService/DeleteDatabase"
	// AdminServiceMountDatabaseProcedure is the fully-qualified name of the AdminService's
	// MountDatabase RPC.
	AdminServiceMountDatabaseProcedure = "/sqlrpc.v1.AdminService/MountDatabase"
	// AdminServiceUnMountDatabaseProcedure is the fully-qualified name of the AdminService's
	// UnMountDatabase RPC.
	AdminServiceUnMountDatabaseProcedure = "/sqlrpc.v1.AdminService/UnMountDatabase"
	// AdminServiceGetServerInfoProcedure is the fully-qualified name of the AdminService's
	// GetServerInfo RPC.
	AdminServiceGetServerInfoProcedure = "/sqlrpc.v1.AdminService/GetServerInfo"
	// AdminServiceLoginProcedure is the fully-qualified name of the AdminService's Login RPC.
	AdminServiceLoginProcedure = "/sqlrpc.v1.AdminService/Login"
	// AdminServiceLogoutProcedure is the fully-qualified name of the AdminService's Logout RPC.
	AdminServiceLogoutProcedure = "/sqlrpc.v1.AdminService/Logout"
	// AdminServiceUpdatePasswordProcedure is the fully-qualified name of the AdminService's
	// UpdatePassword RPC.
	AdminServiceUpdatePasswordProcedure = "/sqlrpc.v1.AdminService/UpdatePassword"
)

// AdminServiceClient is a client for the sqlrpc.v1.AdminService service.
type AdminServiceClient interface {
	// *
	// User Management: List.
	// Returns all system users and their assigned roles.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// *
	// User Management: Create.
	// Provisions a new user identity in the platform.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// User Management: Update Role.
	// Modifies the RBAC tier for an existing user.
	UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error)
	// *
	// User Management: Delete.
	// Permanently removes a user and invalidates all their associated API keys.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// API Key Management: List.
	// Returns all active API keys for a specific user.
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	// *
	// API Key Management: Create.
	// Provisions a new secure API key for authentication.
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	// *
	// API Key Management: Delete.
	// Revokes a specific API key immediately.
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
	// *
	// Database Lifecycle: List.
	// Returns all managed tenant databases in the platform.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Database Lifecycle: Create.
	// Provisions a new, isolated SQLite database for a tenant.
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// *
	// Database Lifecycle: Update.
	// Modifies non-destructive configuration for an existing tenant.
	UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error)
	// *
	// Database Lifecycle: Delete.
	// Permanently removes the database file and its tenant registration.
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
	// *
	// Database Lifecycle: Mount existing.
	// Registers and attaches an existing SQLite file into the platform.
	MountDatabase(context.Context, *connect.Request[v1.MountDatabaseRequest]) (*connect.Response[v1.MountDatabaseResponse], error)
	// *
	// Database Lifecycle: Unmount.
	// Gently removes an active database from the platform without deleting the
	// file.
	UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error)
	// *
	// Platform Info.
	// Returns global system metadata, versioning, and status.
	GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error)
	// *
	// Authentication: Login.
	// Authenticates credentials and yields a session token/API key.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Authentication: Logout.
	// Terminates the active session.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// *
	// User Management: Update Password.
	// Enables a user to modify their own credential or an admin to reset it.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
}

// NewAdminServiceClient constructs a client for the sqlrpc.v1.AdminService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_sqlrpc_v1_admin_service_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+AdminServiceListUsersProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+AdminServiceCreateUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		updateUserRole: connect.NewClient[v1.UpdateUserRoleRequest, v1.UpdateUserRoleResponse](
			httpClient,
			baseURL+AdminServiceUpdateUserRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateUserRole")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+AdminServiceDeleteUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		listAPIKeys: connect.NewClient[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse](
			httpClient,
			baseURL+AdminServiceListAPIKeysProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListAPIKeys")),
			connect.WithClientOptions(opts...),
		),
		createAPIKey: connect.NewClient[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse](
			httpClient,
			baseURL+AdminServiceCreateAPIKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateAPIKey")),
			connect.WithClientOptions(opts...),
		),
		deleteAPIKey: connect.NewClient[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse](
			httpClient,
			baseURL+AdminServiceDeleteAPIKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteAPIKey")),
			connect.WithClientOptions(opts...),
		),
		listDatabases: connect.NewClient[v1.ListDatabasesRequest, v1.ListDatabasesResponse](
			httpClient,
			baseURL+AdminServiceListDatabasesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
			connect.WithClientOptions(opts...),
		),
		createDatabase: connect.NewClient[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse](
			httpClient,
			baseURL+AdminServiceCreateDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateDatabase")),
			connect.WithClientOptions(opts...),
		),
		updateDatabase: connect.NewClient[v1.UpdateDatabaseRequest, v1.UpdateDatabaseResponse](
			httpClient,
			baseURL+AdminServiceUpdateDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateDatabase")),
			connect.WithClientOptions(opts...),
		),
		deleteDatabase: connect.NewClient[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse](
			httpClient,
			baseURL+AdminServiceDeleteDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteDatabase")),
			connect.WithClientOptions(opts...),
		),
		mountDatabase: connect.NewClient[v1.MountDatabaseRequest, v1.MountDatabaseResponse](
			httpClient,
			baseURL+AdminServiceMountDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("MountDatabase")),
			connect.WithClientOptions(opts...),
		),
		unMountDatabase: connect.NewClient[v1.UnMountDatabaseRequest, v1.UnMountDatabaseResponse](
			httpClient,
			baseURL+AdminServiceUnMountDatabaseProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UnMountDatabase")),
			connect.WithClientOptions(opts...),
		),
		getServerInfo: connect.NewClient[v1.GetServerInfoRequest, v1.ServerInfo](
			httpClient,
			baseURL+AdminServiceGetServerInfoProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetServerInfo")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AdminServiceLoginProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AdminServiceLogoutProcedure,
			connect.WithSchema(adminServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		updatePassword: connect.NewClient[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse](
			httpClient,
			baseURL+AdminServiceUpdatePasswordProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	listUsers       *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	createUser      *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	updateUserRole  *connect.Client[v1.UpdateUserRoleRequest, v1.UpdateUserRoleResponse]
	deleteUser      *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	listAPIKeys     *connect.Client[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse]
	createAPIKey    *connect.Client[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse]
	deleteAPIKey    *connect.Client[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse]
	listDatabases   *connect.Client[v1.ListDatabasesRequest, v1.ListDatabasesResponse]
	createDatabase  *connect.Client[v1.CreateDatabaseRequest, v1.CreateDatabaseResponse]
	updateDatabase  *connect.Client[v1.UpdateDatabaseRequest, v1.UpdateDatabaseResponse]
	deleteDatabase  *connect.Client[v1.DeleteDatabaseRequest, v1.DeleteDatabaseResponse]
	mountDatabase   *connect.Client[v1.MountDatabaseRequest, v1.MountDatabaseResponse]
	unMountDatabase *connect.Client[v1.UnMountDatabaseRequest, v1.UnMountDatabaseResponse]
	getServerInfo   *connect.Client[v1.GetServerInfoRequest, v1.ServerInfo]
	login           *connect.Client[v1.LoginRequest, v1.LoginResponse]
	logout          *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
	updatePassword  *connect.Client[v1.UpdatePasswordRequest, v1.UpdatePasswordResponse]
}

// ListUsers calls sqlrpc.v1.AdminService.ListUsers.
func (c *adminServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// CreateUser calls sqlrpc.v1.AdminService.CreateUser.
func (c *adminServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUserRole calls sqlrpc.v1.AdminService.UpdateUserRole.
func (c *adminServiceClient) UpdateUserRole(ctx context.Context, req *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error) {
	return c.updateUserRole.CallUnary(ctx, req)
}

// DeleteUser calls sqlrpc.v1.AdminService.DeleteUser.
func (c *adminServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// ListAPIKeys calls sqlrpc.v1.AdminService.ListAPIKeys.
func (c *adminServiceClient) ListAPIKeys(ctx context.Context, req *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return c.listAPIKeys.CallUnary(ctx, req)
}

// CreateAPIKey calls sqlrpc.v1.AdminService.CreateAPIKey.
func (c *adminServiceClient) CreateAPIKey(ctx context.Context, req *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return c.createAPIKey.CallUnary(ctx, req)
}

// DeleteAPIKey calls sqlrpc.v1.AdminService.DeleteAPIKey.
func (c *adminServiceClient) DeleteAPIKey(ctx context.Context, req *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return c.deleteAPIKey.CallUnary(ctx, req)
}

// ListDatabases calls sqlrpc.v1.AdminService.ListDatabases.
func (c *adminServiceClient) ListDatabases(ctx context.Context, req *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return c.listDatabases.CallUnary(ctx, req)
}

// CreateDatabase calls sqlrpc.v1.AdminService.CreateDatabase.
func (c *adminServiceClient) CreateDatabase(ctx context.Context, req *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return c.createDatabase.CallUnary(ctx, req)
}

// UpdateDatabase calls sqlrpc.v1.AdminService.UpdateDatabase.
func (c *adminServiceClient) UpdateDatabase(ctx context.Context, req *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error) {
	return c.updateDatabase.CallUnary(ctx, req)
}

// DeleteDatabase calls sqlrpc.v1.AdminService.DeleteDatabase.
func (c *adminServiceClient) DeleteDatabase(ctx context.Context, req *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return c.deleteDatabase.CallUnary(ctx, req)
}

// MountDatabase calls sqlrpc.v1.AdminService.MountDatabase.
func (c *adminServiceClient) MountDatabase(ctx context.Context, req *connect.Request[v1.MountDatabaseRequest]) (*connect.Response[v1.MountDatabaseResponse], error) {
	return c.mountDatabase.CallUnary(ctx, req)
}

// UnMountDatabase calls sqlrpc.v1.AdminService.UnMountDatabase.
func (c *adminServiceClient) UnMountDatabase(ctx context.Context, req *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error) {
	return c.unMountDatabase.CallUnary(ctx, req)
}

// GetServerInfo calls sqlrpc.v1.AdminService.GetServerInfo.
func (c *adminServiceClient) GetServerInfo(ctx context.Context, req *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error) {
	return c.getServerInfo.CallUnary(ctx, req)
}

// Login calls sqlrpc.v1.AdminService.Login.
func (c *adminServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls sqlrpc.v1.AdminService.Logout.
func (c *adminServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// UpdatePassword calls sqlrpc.v1.AdminService.UpdatePassword.
func (c *adminServiceClient) UpdatePassword(ctx context.Context, req *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return c.updatePassword.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the sqlrpc.v1.AdminService service.
type AdminServiceHandler interface {
	// *
	// User Management: List.
	// Returns all system users and their assigned roles.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// *
	// User Management: Create.
	// Provisions a new user identity in the platform.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// *
	// User Management: Update Role.
	// Modifies the RBAC tier for an existing user.
	UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error)
	// *
	// User Management: Delete.
	// Permanently removes a user and invalidates all their associated API keys.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// *
	// API Key Management: List.
	// Returns all active API keys for a specific user.
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	// *
	// API Key Management: Create.
	// Provisions a new secure API key for authentication.
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	// *
	// API Key Management: Delete.
	// Revokes a specific API key immediately.
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
	// *
	// Database Lifecycle: List.
	// Returns all managed tenant databases in the platform.
	ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error)
	// *
	// Database Lifecycle: Create.
	// Provisions a new, isolated SQLite database for a tenant.
	CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error)
	// *
	// Database Lifecycle: Update.
	// Modifies non-destructive configuration for an existing tenant.
	UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error)
	// *
	// Database Lifecycle: Delete.
	// Permanently removes the database file and its tenant registration.
	DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error)
	// *
	// Database Lifecycle: Mount existing.
	// Registers and attaches an existing SQLite file into the platform.
	MountDatabase(context.Context, *connect.Request[v1.MountDatabaseRequest]) (*connect.Response[v1.MountDatabaseResponse], error)
	// *
	// Database Lifecycle: Unmount.
	// Gently removes an active database from the platform without deleting the
	// file.
	UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error)
	// *
	// Platform Info.
	// Returns global system metadata, versioning, and status.
	GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error)
	// *
	// Authentication: Login.
	// Authenticates credentials and yields a session token/API key.
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// *
	// Authentication: Logout.
	// Terminates the active session.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	// *
	// User Management: Update Password.
	// Enables a user to modify their own credential or an admin to reset it.
	UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_sqlrpc_v1_admin_service_proto.Services().ByName("AdminService").Methods()
	adminServiceListUsersHandler := connect.NewUnaryHandler(
		AdminServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(adminServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateUserHandler := connect.NewUnaryHandler(
		AdminServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(adminServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateUserRoleHandler := connect.NewUnaryHandler(
		AdminServiceUpdateUserRoleProcedure,
		svc.UpdateUserRole,
		connect.WithSchema(adminServiceMethods.ByName("UpdateUserRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUserHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListAPIKeysHandler := connect.NewUnaryHandler(
		AdminServiceListAPIKeysProcedure,
		svc.ListAPIKeys,
		connect.WithSchema(adminServiceMethods.ByName("ListAPIKeys")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateAPIKeyHandler := connect.NewUnaryHandler(
		AdminServiceCreateAPIKeyProcedure,
		svc.CreateAPIKey,
		connect.WithSchema(adminServiceMethods.ByName("CreateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteAPIKeyHandler := connect.NewUnaryHandler(
		AdminServiceDeleteAPIKeyProcedure,
		svc.DeleteAPIKey,
		connect.WithSchema(adminServiceMethods.ByName("DeleteAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListDatabasesHandler := connect.NewUnaryHandler(
		AdminServiceListDatabasesProcedure,
		svc.ListDatabases,
		connect.WithSchema(adminServiceMethods.ByName("ListDatabases")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceCreateDatabaseProcedure,
		svc.CreateDatabase,
		connect.WithSchema(adminServiceMethods.ByName("CreateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceUpdateDatabaseProcedure,
		svc.UpdateDatabase,
		connect.WithSchema(adminServiceMethods.ByName("UpdateDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceDeleteDatabaseProcedure,
		svc.DeleteDatabase,
		connect.WithSchema(adminServiceMethods.ByName("DeleteDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceMountDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceMountDatabaseProcedure,
		svc.MountDatabase,
		connect.WithSchema(adminServiceMethods.ByName("MountDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUnMountDatabaseHandler := connect.NewUnaryHandler(
		AdminServiceUnMountDatabaseProcedure,
		svc.UnMountDatabase,
		connect.WithSchema(adminServiceMethods.ByName("UnMountDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetServerInfoHandler := connect.NewUnaryHandler(
		AdminServiceGetServerInfoProcedure,
		svc.GetServerInfo,
		connect.WithSchema(adminServiceMethods.ByName("GetServerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceLoginHandler := connect.NewUnaryHandler(
		AdminServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(adminServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceLogoutHandler := connect.NewUnaryHandler(
		AdminServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(adminServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdatePasswordHandler := connect.NewUnaryHandler(
		AdminServiceUpdatePasswordProcedure,
		svc.UpdatePassword,
		connect.WithSchema(adminServiceMethods.ByName("UpdatePassword")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sqlrpc.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceListUsersProcedure:
			adminServiceListUsersHandler.ServeHTTP(w, r)
		case AdminServiceCreateUserProcedure:
			adminServiceCreateUserHandler.ServeHTTP(w, r)
		case AdminServiceUpdateUserRoleProcedure:
			adminServiceUpdateUserRoleHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUserProcedure:
			adminServiceDeleteUserHandler.ServeHTTP(w, r)
		case AdminServiceListAPIKeysProcedure:
			adminServiceListAPIKeysHandler.ServeHTTP(w, r)
		case AdminServiceCreateAPIKeyProcedure:
			adminServiceCreateAPIKeyHandler.ServeHTTP(w, r)
		case AdminServiceDeleteAPIKeyProcedure:
			adminServiceDeleteAPIKeyHandler.ServeHTTP(w, r)
		case AdminServiceListDatabasesProcedure:
			adminServiceListDatabasesHandler.ServeHTTP(w, r)
		case AdminServiceCreateDatabaseProcedure:
			adminServiceCreateDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceUpdateDatabaseProcedure:
			adminServiceUpdateDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceDeleteDatabaseProcedure:
			adminServiceDeleteDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceMountDatabaseProcedure:
			adminServiceMountDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceUnMountDatabaseProcedure:
			adminServiceUnMountDatabaseHandler.ServeHTTP(w, r)
		case AdminServiceGetServerInfoProcedure:
			adminServiceGetServerInfoHandler.ServeHTTP(w, r)
		case AdminServiceLoginProcedure:
			adminServiceLoginHandler.ServeHTTP(w, r)
		case AdminServiceLogoutProcedure:
			adminServiceLogoutHandler.ServeHTTP(w, r)
		case AdminServiceUpdatePasswordProcedure:
			adminServiceUpdatePasswordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.ListUsers is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.CreateUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.UpdateUserRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.DeleteUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.ListAPIKeys is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.CreateAPIKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.DeleteAPIKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListDatabases(context.Context, *connect.Request[v1.ListDatabasesRequest]) (*connect.Response[v1.ListDatabasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.ListDatabases is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateDatabase(context.Context, *connect.Request[v1.CreateDatabaseRequest]) (*connect.Response[v1.CreateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.CreateDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateDatabase(context.Context, *connect.Request[v1.UpdateDatabaseRequest]) (*connect.Response[v1.UpdateDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.UpdateDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteDatabase(context.Context, *connect.Request[v1.DeleteDatabaseRequest]) (*connect.Response[v1.DeleteDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.DeleteDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) MountDatabase(context.Context, *connect.Request[v1.MountDatabaseRequest]) (*connect.Response[v1.MountDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.MountDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) UnMountDatabase(context.Context, *connect.Request[v1.UnMountDatabaseRequest]) (*connect.Response[v1.UnMountDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.UnMountDatabase is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.GetServerInfo is not implemented"))
}

func (UnimplementedAdminServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.Login is not implemented"))
}

func (UnimplementedAdminServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.Logout is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdatePassword(context.Context, *connect.Request[v1.UpdatePasswordRequest]) (*connect.Response[v1.UpdatePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.AdminService.UpdatePassword is not implemented"))
}
