// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sqlrpc/v1/db_service.proto

package sqlrpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sqlite-server/internal/protos/sqlrpc/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatabaseServiceName is the fully-qualified name of the DatabaseService service.
	DatabaseServiceName = "sqlrpc.v1.DatabaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatabaseServiceQueryProcedure is the fully-qualified name of the DatabaseService's Query RPC.
	DatabaseServiceQueryProcedure = "/sqlrpc.v1.DatabaseService/Query"
	// DatabaseServiceExecProcedure is the fully-qualified name of the DatabaseService's Exec RPC.
	DatabaseServiceExecProcedure = "/sqlrpc.v1.DatabaseService/Exec"
	// DatabaseServiceQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// QueryStream RPC.
	DatabaseServiceQueryStreamProcedure = "/sqlrpc.v1.DatabaseService/QueryStream"
	// DatabaseServiceTransactionProcedure is the fully-qualified name of the DatabaseService's
	// Transaction RPC.
	DatabaseServiceTransactionProcedure = "/sqlrpc.v1.DatabaseService/Transaction"
	// DatabaseServiceBeginTransactionProcedure is the fully-qualified name of the DatabaseService's
	// BeginTransaction RPC.
	DatabaseServiceBeginTransactionProcedure = "/sqlrpc.v1.DatabaseService/BeginTransaction"
	// DatabaseServiceTransactionQueryProcedure is the fully-qualified name of the DatabaseService's
	// TransactionQuery RPC.
	DatabaseServiceTransactionQueryProcedure = "/sqlrpc.v1.DatabaseService/TransactionQuery"
	// DatabaseServiceTransactionExecProcedure is the fully-qualified name of the DatabaseService's
	// TransactionExec RPC.
	DatabaseServiceTransactionExecProcedure = "/sqlrpc.v1.DatabaseService/TransactionExec"
	// DatabaseServiceTransactionQueryStreamProcedure is the fully-qualified name of the
	// DatabaseService's TransactionQueryStream RPC.
	DatabaseServiceTransactionQueryStreamProcedure = "/sqlrpc.v1.DatabaseService/TransactionQueryStream"
	// DatabaseServiceTransactionSavepointProcedure is the fully-qualified name of the DatabaseService's
	// TransactionSavepoint RPC.
	DatabaseServiceTransactionSavepointProcedure = "/sqlrpc.v1.DatabaseService/TransactionSavepoint"
	// DatabaseServiceCommitTransactionProcedure is the fully-qualified name of the DatabaseService's
	// CommitTransaction RPC.
	DatabaseServiceCommitTransactionProcedure = "/sqlrpc.v1.DatabaseService/CommitTransaction"
	// DatabaseServiceRollbackTransactionProcedure is the fully-qualified name of the DatabaseService's
	// RollbackTransaction RPC.
	DatabaseServiceRollbackTransactionProcedure = "/sqlrpc.v1.DatabaseService/RollbackTransaction"
	// DatabaseServiceExecuteTransactionProcedure is the fully-qualified name of the DatabaseService's
	// ExecuteTransaction RPC.
	DatabaseServiceExecuteTransactionProcedure = "/sqlrpc.v1.DatabaseService/ExecuteTransaction"
	// DatabaseServiceTypedQueryProcedure is the fully-qualified name of the DatabaseService's
	// TypedQuery RPC.
	DatabaseServiceTypedQueryProcedure = "/sqlrpc.v1.DatabaseService/TypedQuery"
	// DatabaseServiceTypedExecProcedure is the fully-qualified name of the DatabaseService's TypedExec
	// RPC.
	DatabaseServiceTypedExecProcedure = "/sqlrpc.v1.DatabaseService/TypedExec"
	// DatabaseServiceTypedQueryStreamProcedure is the fully-qualified name of the DatabaseService's
	// TypedQueryStream RPC.
	DatabaseServiceTypedQueryStreamProcedure = "/sqlrpc.v1.DatabaseService/TypedQueryStream"
	// DatabaseServiceTypedTransactionQueryProcedure is the fully-qualified name of the
	// DatabaseService's TypedTransactionQuery RPC.
	DatabaseServiceTypedTransactionQueryProcedure = "/sqlrpc.v1.DatabaseService/TypedTransactionQuery"
	// DatabaseServiceTypedTransactionExecProcedure is the fully-qualified name of the DatabaseService's
	// TypedTransactionExec RPC.
	DatabaseServiceTypedTransactionExecProcedure = "/sqlrpc.v1.DatabaseService/TypedTransactionExec"
	// DatabaseServiceTypedTransactionQueryStreamProcedure is the fully-qualified name of the
	// DatabaseService's TypedTransactionQueryStream RPC.
	DatabaseServiceTypedTransactionQueryStreamProcedure = "/sqlrpc.v1.DatabaseService/TypedTransactionQueryStream"
	// DatabaseServiceExplainProcedure is the fully-qualified name of the DatabaseService's Explain RPC.
	DatabaseServiceExplainProcedure = "/sqlrpc.v1.DatabaseService/Explain"
	// DatabaseServiceTypedExplainProcedure is the fully-qualified name of the DatabaseService's
	// TypedExplain RPC.
	DatabaseServiceTypedExplainProcedure = "/sqlrpc.v1.DatabaseService/TypedExplain"
	// DatabaseServiceListTablesProcedure is the fully-qualified name of the DatabaseService's
	// ListTables RPC.
	DatabaseServiceListTablesProcedure = "/sqlrpc.v1.DatabaseService/ListTables"
	// DatabaseServiceGetTableSchemaProcedure is the fully-qualified name of the DatabaseService's
	// GetTableSchema RPC.
	DatabaseServiceGetTableSchemaProcedure = "/sqlrpc.v1.DatabaseService/GetTableSchema"
	// DatabaseServiceGetDatabaseSchemaProcedure is the fully-qualified name of the DatabaseService's
	// GetDatabaseSchema RPC.
	DatabaseServiceGetDatabaseSchemaProcedure = "/sqlrpc.v1.DatabaseService/GetDatabaseSchema"
	// DatabaseServiceVacuumProcedure is the fully-qualified name of the DatabaseService's Vacuum RPC.
	DatabaseServiceVacuumProcedure = "/sqlrpc.v1.DatabaseService/Vacuum"
	// DatabaseServiceCheckpointProcedure is the fully-qualified name of the DatabaseService's
	// Checkpoint RPC.
	DatabaseServiceCheckpointProcedure = "/sqlrpc.v1.DatabaseService/Checkpoint"
	// DatabaseServiceIntegrityCheckProcedure is the fully-qualified name of the DatabaseService's
	// IntegrityCheck RPC.
	DatabaseServiceIntegrityCheckProcedure = "/sqlrpc.v1.DatabaseService/IntegrityCheck"
	// DatabaseServiceAttachDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// AttachDatabase RPC.
	DatabaseServiceAttachDatabaseProcedure = "/sqlrpc.v1.DatabaseService/AttachDatabase"
	// DatabaseServiceDetachDatabaseProcedure is the fully-qualified name of the DatabaseService's
	// DetachDatabase RPC.
	DatabaseServiceDetachDatabaseProcedure = "/sqlrpc.v1.DatabaseService/DetachDatabase"
	// DatabaseServiceListExtensionsProcedure is the fully-qualified name of the DatabaseService's
	// ListExtensions RPC.
	DatabaseServiceListExtensionsProcedure = "/sqlrpc.v1.DatabaseService/ListExtensions"
	// DatabaseServiceLoadExtensionProcedure is the fully-qualified name of the DatabaseService's
	// LoadExtension RPC.
	DatabaseServiceLoadExtensionProcedure = "/sqlrpc.v1.DatabaseService/LoadExtension"
)

// DatabaseServiceClient is a client for the sqlrpc.v1.DatabaseService service.
type DatabaseServiceClient interface {
	// *
	// Read Endpoint (Unary).
	// Uses the global shared LRU connection pool, routing to a Read-Only
	// connection for ROLE_READ_ONLY users.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Write Endpoint (Unary DML).
	// Uses the global shared LRU connection pool, strictly routing to a
	// Read-Write connection. Denied for ROLE_READ_ONLY.
	Exec(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Read Endpoint (Streaming).
	// Routed via the shared LRU pool to a Read-Only connection. Yields chunked
	// results.
	QueryStream(context.Context, *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Bidirectional Streaming Transaction.
	// Maintains a persistent, multiplexed stream for executing multiple
	// statements sequentially under a single transaction, holding the shared LRU
	// connection until completion.
	Transaction(context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse]
	// *
	// Transaction Control.
	// Acquires an active connection from the global shared LRU pool based on the
	// user's role (RO vs RW).
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Read Endpoint within a Transaction.
	// Inherits the active transaction context tied to the shared LRU connection
	// pool.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Write Endpoint within a Transaction.
	// Fails if the underlying transaction connection is Read-Only.
	TransactionExec(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Read Endpoint (Streaming) within a Transaction.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error)
	// *
	// Savepoint Control within a Transaction.
	// Enables nested transaction boundaries (SAVEPOINT, RELEASE, ROLLBACK TO)
	// within an active Unary ID-Based transaction.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Transaction Commit.
	// Commits an active Unary ID-Based transaction and releases the connection
	// back to the shared LRU pool.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Transaction Rollback.
	// Rolls back an active Unary ID-Based transaction and releases the connection
	// back to the shared LRU pool.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Atomic Script Execution.
	// Executes a predefined sequence of queries within a single transaction
	// atomically. Handled completely server-side to minimize network latency
	// between statements.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
	// *
	// Typed Read Endpoint (Unary).
	// Automatically routed to a Read-Only replica connection for ROLE_READ_ONLY
	// users.
	TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Typed Write Endpoint (Unary DML).
	// Uses the global shared LRU connection pool, strictly routing to a
	// Read-Write connection.
	TypedExec(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Typed Read Endpoint (Streaming).
	// Routes to the global Read-Only or Read-Write LRU connection depending on
	// user role.
	TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error)
	// *
	// Typed Read Endpoint within a Transaction.
	TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Typed Write Endpoint within a Transaction.
	// Denied on Read-Only transactions.
	TypedTransactionExec(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Streaming Interface.
	// Yields partitioned tenant data blocks over a managed stream.
	TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error)
	// *
	// Introspection: Query Plan Explanation.
	// Returns the EXPLAIN QUERY PLAN breakdown for a given statement without
	// running the statement itself.
	Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Typed Introspection: Query Plan Explanation.
	// Provides the EXPLAIN QUERY PLAN breakdown using strictly-typed parameters.
	TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Database Introspection: List Tables.
	// Returns a list of all table names currently present in the target database.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// *
	// Database Introspection: Get Table Schema.
	// Returns the structural schema definitions for a specific table.
	GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error)
	// *
	// Database Introspection: Get Database Schema.
	// Returns the structural schema definitions for the entire underlying
	// database.
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error)
	// *
	// Maintenance: Vacuum.
	// Rebuilds the database file, repacking it into a minimal amount of disk
	// space.
	Vacuum(context.Context, *connect.Request[v1.VacuumRequest]) (*connect.Response[v1.VacuumResponse], error)
	// *
	// Maintenance: Checkpoint.
	// Synchronizes the write-ahead log (WAL) with the main database file.
	Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.CheckpointResponse], error)
	// *
	// Maintenance: Integrity Check.
	// Runs PRAGMA integrity_check to scan for out-of-order records, missing
	// pages, or corruption.
	IntegrityCheck(context.Context, *connect.Request[v1.IntegrityCheckRequest]) (*connect.Response[v1.IntegrityCheckResponse], error)
	// *
	// Maintenance: Attach Database.
	// Dynamically mounts a secondary database into the current tenant's namespace
	// context.
	AttachDatabase(context.Context, *connect.Request[v1.AttachDatabaseRequest]) (*connect.Response[v1.AttachDatabaseResponse], error)
	// *
	// Maintenance: Detach Database.
	// Safely detaches a previously attached secondary database from the active
	// context.
	DetachDatabase(context.Context, *connect.Request[v1.DetachDatabaseRequest]) (*connect.Response[v1.DetachDatabaseResponse], error)
	// *
	// Extensions: List.
	// Returns a catalog of available and loaded SQLite extensions.
	ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error)
	// *
	// Extensions: Load.
	// Dynamically loads a compatible SQLite extension into the target database.
	LoadExtension(context.Context, *connect.Request[v1.LoadExtensionRequest]) (*connect.Response[v1.LoadExtensionResponse], error)
}

// NewDatabaseServiceClient constructs a client for the sqlrpc.v1.DatabaseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatabaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatabaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	databaseServiceMethods := v1.File_sqlrpc_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	return &databaseServiceClient{
		query: connect.NewClient[v1.QueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[v1.QueryRequest, v1.ExecResponse](
			httpClient,
			baseURL+DatabaseServiceExecProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		queryStream: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
			connect.WithClientOptions(opts...),
		),
		transaction: connect.NewClient[v1.TransactionRequest, v1.TransactionResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
			connect.WithClientOptions(opts...),
		),
		beginTransaction: connect.NewClient[v1.BeginTransactionRequest, v1.BeginTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceBeginTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
			connect.WithClientOptions(opts...),
		),
		transactionQuery: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResult](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		transactionExec: connect.NewClient[v1.TransactionQueryRequest, v1.ExecResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionExecProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionExec")),
			connect.WithClientOptions(opts...),
		),
		transactionQueryStream: connect.NewClient[v1.TransactionQueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
			connect.WithClientOptions(opts...),
		),
		transactionSavepoint: connect.NewClient[v1.TransactionSavepointRequest, v1.SavepointResponse](
			httpClient,
			baseURL+DatabaseServiceTransactionSavepointProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
			connect.WithClientOptions(opts...),
		),
		commitTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceCommitTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
			connect.WithClientOptions(opts...),
		),
		rollbackTransaction: connect.NewClient[v1.TransactionControlRequest, v1.TransactionControlResponse](
			httpClient,
			baseURL+DatabaseServiceRollbackTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
			connect.WithClientOptions(opts...),
		),
		executeTransaction: connect.NewClient[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse](
			httpClient,
			baseURL+DatabaseServiceExecuteTransactionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
			connect.WithClientOptions(opts...),
		),
		typedQuery: connect.NewClient[v1.TypedQueryRequest, v1.TypedQueryResult](
			httpClient,
			baseURL+DatabaseServiceTypedQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedQuery")),
			connect.WithClientOptions(opts...),
		),
		typedExec: connect.NewClient[v1.TypedQueryRequest, v1.ExecResponse](
			httpClient,
			baseURL+DatabaseServiceTypedExecProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedExec")),
			connect.WithClientOptions(opts...),
		),
		typedQueryStream: connect.NewClient[v1.TypedQueryRequest, v1.TypedQueryResponse](
			httpClient,
			baseURL+DatabaseServiceTypedQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedQueryStream")),
			connect.WithClientOptions(opts...),
		),
		typedTransactionQuery: connect.NewClient[v1.TypedTransactionQueryRequest, v1.TypedQueryResult](
			httpClient,
			baseURL+DatabaseServiceTypedTransactionQueryProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQuery")),
			connect.WithClientOptions(opts...),
		),
		typedTransactionExec: connect.NewClient[v1.TypedTransactionQueryRequest, v1.ExecResponse](
			httpClient,
			baseURL+DatabaseServiceTypedTransactionExecProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionExec")),
			connect.WithClientOptions(opts...),
		),
		typedTransactionQueryStream: connect.NewClient[v1.TypedTransactionQueryRequest, v1.TypedQueryResponse](
			httpClient,
			baseURL+DatabaseServiceTypedTransactionQueryStreamProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQueryStream")),
			connect.WithClientOptions(opts...),
		),
		explain: connect.NewClient[v1.QueryRequest, v1.ExplainResponse](
			httpClient,
			baseURL+DatabaseServiceExplainProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Explain")),
			connect.WithClientOptions(opts...),
		),
		typedExplain: connect.NewClient[v1.TypedQueryRequest, v1.ExplainResponse](
			httpClient,
			baseURL+DatabaseServiceTypedExplainProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("TypedExplain")),
			connect.WithClientOptions(opts...),
		),
		listTables: connect.NewClient[v1.ListTablesRequest, v1.ListTablesResponse](
			httpClient,
			baseURL+DatabaseServiceListTablesProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
			connect.WithClientOptions(opts...),
		),
		getTableSchema: connect.NewClient[v1.GetTableSchemaRequest, v1.TableSchema](
			httpClient,
			baseURL+DatabaseServiceGetTableSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetTableSchema")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseSchema: connect.NewClient[v1.GetDatabaseSchemaRequest, v1.DatabaseSchema](
			httpClient,
			baseURL+DatabaseServiceGetDatabaseSchemaProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
			connect.WithClientOptions(opts...),
		),
		vacuum: connect.NewClient[v1.VacuumRequest, v1.VacuumResponse](
			httpClient,
			baseURL+DatabaseServiceVacuumProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Vacuum")),
			connect.WithClientOptions(opts...),
		),
		checkpoint: connect.NewClient[v1.CheckpointRequest, v1.CheckpointResponse](
			httpClient,
			baseURL+DatabaseServiceCheckpointProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("Checkpoint")),
			connect.WithClientOptions(opts...),
		),
		integrityCheck: connect.NewClient[v1.IntegrityCheckRequest, v1.IntegrityCheckResponse](
			httpClient,
			baseURL+DatabaseServiceIntegrityCheckProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("IntegrityCheck")),
			connect.WithClientOptions(opts...),
		),
		attachDatabase: connect.NewClient[v1.AttachDatabaseRequest, v1.AttachDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceAttachDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("AttachDatabase")),
			connect.WithClientOptions(opts...),
		),
		detachDatabase: connect.NewClient[v1.DetachDatabaseRequest, v1.DetachDatabaseResponse](
			httpClient,
			baseURL+DatabaseServiceDetachDatabaseProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("DetachDatabase")),
			connect.WithClientOptions(opts...),
		),
		listExtensions: connect.NewClient[v1.ListExtensionsRequest, v1.ListExtensionsResponse](
			httpClient,
			baseURL+DatabaseServiceListExtensionsProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("ListExtensions")),
			connect.WithClientOptions(opts...),
		),
		loadExtension: connect.NewClient[v1.LoadExtensionRequest, v1.LoadExtensionResponse](
			httpClient,
			baseURL+DatabaseServiceLoadExtensionProcedure,
			connect.WithSchema(databaseServiceMethods.ByName("LoadExtension")),
			connect.WithClientOptions(opts...),
		),
	}
}

// databaseServiceClient implements DatabaseServiceClient.
type databaseServiceClient struct {
	query                       *connect.Client[v1.QueryRequest, v1.QueryResult]
	exec                        *connect.Client[v1.QueryRequest, v1.ExecResponse]
	queryStream                 *connect.Client[v1.QueryRequest, v1.QueryResponse]
	transaction                 *connect.Client[v1.TransactionRequest, v1.TransactionResponse]
	beginTransaction            *connect.Client[v1.BeginTransactionRequest, v1.BeginTransactionResponse]
	transactionQuery            *connect.Client[v1.TransactionQueryRequest, v1.QueryResult]
	transactionExec             *connect.Client[v1.TransactionQueryRequest, v1.ExecResponse]
	transactionQueryStream      *connect.Client[v1.TransactionQueryRequest, v1.QueryResponse]
	transactionSavepoint        *connect.Client[v1.TransactionSavepointRequest, v1.SavepointResponse]
	commitTransaction           *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	rollbackTransaction         *connect.Client[v1.TransactionControlRequest, v1.TransactionControlResponse]
	executeTransaction          *connect.Client[v1.ExecuteTransactionRequest, v1.ExecuteTransactionResponse]
	typedQuery                  *connect.Client[v1.TypedQueryRequest, v1.TypedQueryResult]
	typedExec                   *connect.Client[v1.TypedQueryRequest, v1.ExecResponse]
	typedQueryStream            *connect.Client[v1.TypedQueryRequest, v1.TypedQueryResponse]
	typedTransactionQuery       *connect.Client[v1.TypedTransactionQueryRequest, v1.TypedQueryResult]
	typedTransactionExec        *connect.Client[v1.TypedTransactionQueryRequest, v1.ExecResponse]
	typedTransactionQueryStream *connect.Client[v1.TypedTransactionQueryRequest, v1.TypedQueryResponse]
	explain                     *connect.Client[v1.QueryRequest, v1.ExplainResponse]
	typedExplain                *connect.Client[v1.TypedQueryRequest, v1.ExplainResponse]
	listTables                  *connect.Client[v1.ListTablesRequest, v1.ListTablesResponse]
	getTableSchema              *connect.Client[v1.GetTableSchemaRequest, v1.TableSchema]
	getDatabaseSchema           *connect.Client[v1.GetDatabaseSchemaRequest, v1.DatabaseSchema]
	vacuum                      *connect.Client[v1.VacuumRequest, v1.VacuumResponse]
	checkpoint                  *connect.Client[v1.CheckpointRequest, v1.CheckpointResponse]
	integrityCheck              *connect.Client[v1.IntegrityCheckRequest, v1.IntegrityCheckResponse]
	attachDatabase              *connect.Client[v1.AttachDatabaseRequest, v1.AttachDatabaseResponse]
	detachDatabase              *connect.Client[v1.DetachDatabaseRequest, v1.DetachDatabaseResponse]
	listExtensions              *connect.Client[v1.ListExtensionsRequest, v1.ListExtensionsResponse]
	loadExtension               *connect.Client[v1.LoadExtensionRequest, v1.LoadExtensionResponse]
}

// Query calls sqlrpc.v1.DatabaseService.Query.
func (c *databaseServiceClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.query.CallUnary(ctx, req)
}

// Exec calls sqlrpc.v1.DatabaseService.Exec.
func (c *databaseServiceClient) Exec(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// QueryStream calls sqlrpc.v1.DatabaseService.QueryStream.
func (c *databaseServiceClient) QueryStream(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.queryStream.CallServerStream(ctx, req)
}

// Transaction calls sqlrpc.v1.DatabaseService.Transaction.
func (c *databaseServiceClient) Transaction(ctx context.Context) *connect.BidiStreamForClient[v1.TransactionRequest, v1.TransactionResponse] {
	return c.transaction.CallBidiStream(ctx)
}

// BeginTransaction calls sqlrpc.v1.DatabaseService.BeginTransaction.
func (c *databaseServiceClient) BeginTransaction(ctx context.Context, req *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return c.beginTransaction.CallUnary(ctx, req)
}

// TransactionQuery calls sqlrpc.v1.DatabaseService.TransactionQuery.
func (c *databaseServiceClient) TransactionQuery(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return c.transactionQuery.CallUnary(ctx, req)
}

// TransactionExec calls sqlrpc.v1.DatabaseService.TransactionExec.
func (c *databaseServiceClient) TransactionExec(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.transactionExec.CallUnary(ctx, req)
}

// TransactionQueryStream calls sqlrpc.v1.DatabaseService.TransactionQueryStream.
func (c *databaseServiceClient) TransactionQueryStream(ctx context.Context, req *connect.Request[v1.TransactionQueryRequest]) (*connect.ServerStreamForClient[v1.QueryResponse], error) {
	return c.transactionQueryStream.CallServerStream(ctx, req)
}

// TransactionSavepoint calls sqlrpc.v1.DatabaseService.TransactionSavepoint.
func (c *databaseServiceClient) TransactionSavepoint(ctx context.Context, req *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return c.transactionSavepoint.CallUnary(ctx, req)
}

// CommitTransaction calls sqlrpc.v1.DatabaseService.CommitTransaction.
func (c *databaseServiceClient) CommitTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.commitTransaction.CallUnary(ctx, req)
}

// RollbackTransaction calls sqlrpc.v1.DatabaseService.RollbackTransaction.
func (c *databaseServiceClient) RollbackTransaction(ctx context.Context, req *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return c.rollbackTransaction.CallUnary(ctx, req)
}

// ExecuteTransaction calls sqlrpc.v1.DatabaseService.ExecuteTransaction.
func (c *databaseServiceClient) ExecuteTransaction(ctx context.Context, req *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return c.executeTransaction.CallUnary(ctx, req)
}

// TypedQuery calls sqlrpc.v1.DatabaseService.TypedQuery.
func (c *databaseServiceClient) TypedQuery(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return c.typedQuery.CallUnary(ctx, req)
}

// TypedExec calls sqlrpc.v1.DatabaseService.TypedExec.
func (c *databaseServiceClient) TypedExec(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.typedExec.CallUnary(ctx, req)
}

// TypedQueryStream calls sqlrpc.v1.DatabaseService.TypedQueryStream.
func (c *databaseServiceClient) TypedQueryStream(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error) {
	return c.typedQueryStream.CallServerStream(ctx, req)
}

// TypedTransactionQuery calls sqlrpc.v1.DatabaseService.TypedTransactionQuery.
func (c *databaseServiceClient) TypedTransactionQuery(ctx context.Context, req *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return c.typedTransactionQuery.CallUnary(ctx, req)
}

// TypedTransactionExec calls sqlrpc.v1.DatabaseService.TypedTransactionExec.
func (c *databaseServiceClient) TypedTransactionExec(ctx context.Context, req *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return c.typedTransactionExec.CallUnary(ctx, req)
}

// TypedTransactionQueryStream calls sqlrpc.v1.DatabaseService.TypedTransactionQueryStream.
func (c *databaseServiceClient) TypedTransactionQueryStream(ctx context.Context, req *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.ServerStreamForClient[v1.TypedQueryResponse], error) {
	return c.typedTransactionQueryStream.CallServerStream(ctx, req)
}

// Explain calls sqlrpc.v1.DatabaseService.Explain.
func (c *databaseServiceClient) Explain(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return c.explain.CallUnary(ctx, req)
}

// TypedExplain calls sqlrpc.v1.DatabaseService.TypedExplain.
func (c *databaseServiceClient) TypedExplain(ctx context.Context, req *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return c.typedExplain.CallUnary(ctx, req)
}

// ListTables calls sqlrpc.v1.DatabaseService.ListTables.
func (c *databaseServiceClient) ListTables(ctx context.Context, req *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return c.listTables.CallUnary(ctx, req)
}

// GetTableSchema calls sqlrpc.v1.DatabaseService.GetTableSchema.
func (c *databaseServiceClient) GetTableSchema(ctx context.Context, req *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error) {
	return c.getTableSchema.CallUnary(ctx, req)
}

// GetDatabaseSchema calls sqlrpc.v1.DatabaseService.GetDatabaseSchema.
func (c *databaseServiceClient) GetDatabaseSchema(ctx context.Context, req *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error) {
	return c.getDatabaseSchema.CallUnary(ctx, req)
}

// Vacuum calls sqlrpc.v1.DatabaseService.Vacuum.
func (c *databaseServiceClient) Vacuum(ctx context.Context, req *connect.Request[v1.VacuumRequest]) (*connect.Response[v1.VacuumResponse], error) {
	return c.vacuum.CallUnary(ctx, req)
}

// Checkpoint calls sqlrpc.v1.DatabaseService.Checkpoint.
func (c *databaseServiceClient) Checkpoint(ctx context.Context, req *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.CheckpointResponse], error) {
	return c.checkpoint.CallUnary(ctx, req)
}

// IntegrityCheck calls sqlrpc.v1.DatabaseService.IntegrityCheck.
func (c *databaseServiceClient) IntegrityCheck(ctx context.Context, req *connect.Request[v1.IntegrityCheckRequest]) (*connect.Response[v1.IntegrityCheckResponse], error) {
	return c.integrityCheck.CallUnary(ctx, req)
}

// AttachDatabase calls sqlrpc.v1.DatabaseService.AttachDatabase.
func (c *databaseServiceClient) AttachDatabase(ctx context.Context, req *connect.Request[v1.AttachDatabaseRequest]) (*connect.Response[v1.AttachDatabaseResponse], error) {
	return c.attachDatabase.CallUnary(ctx, req)
}

// DetachDatabase calls sqlrpc.v1.DatabaseService.DetachDatabase.
func (c *databaseServiceClient) DetachDatabase(ctx context.Context, req *connect.Request[v1.DetachDatabaseRequest]) (*connect.Response[v1.DetachDatabaseResponse], error) {
	return c.detachDatabase.CallUnary(ctx, req)
}

// ListExtensions calls sqlrpc.v1.DatabaseService.ListExtensions.
func (c *databaseServiceClient) ListExtensions(ctx context.Context, req *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error) {
	return c.listExtensions.CallUnary(ctx, req)
}

// LoadExtension calls sqlrpc.v1.DatabaseService.LoadExtension.
func (c *databaseServiceClient) LoadExtension(ctx context.Context, req *connect.Request[v1.LoadExtensionRequest]) (*connect.Response[v1.LoadExtensionResponse], error) {
	return c.loadExtension.CallUnary(ctx, req)
}

// DatabaseServiceHandler is an implementation of the sqlrpc.v1.DatabaseService service.
type DatabaseServiceHandler interface {
	// *
	// Read Endpoint (Unary).
	// Uses the global shared LRU connection pool, routing to a Read-Only
	// connection for ROLE_READ_ONLY users.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Write Endpoint (Unary DML).
	// Uses the global shared LRU connection pool, strictly routing to a
	// Read-Write connection. Denied for ROLE_READ_ONLY.
	Exec(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Read Endpoint (Streaming).
	// Routed via the shared LRU pool to a Read-Only connection. Yields chunked
	// results.
	QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Bidirectional Streaming Transaction.
	// Maintains a persistent, multiplexed stream for executing multiple
	// statements sequentially under a single transaction, holding the shared LRU
	// connection until completion.
	Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error
	// *
	// Transaction Control.
	// Acquires an active connection from the global shared LRU pool based on the
	// user's role (RO vs RW).
	BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error)
	// *
	// Read Endpoint within a Transaction.
	// Inherits the active transaction context tied to the shared LRU connection
	// pool.
	TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error)
	// *
	// Write Endpoint within a Transaction.
	// Fails if the underlying transaction connection is Read-Only.
	TransactionExec(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Read Endpoint (Streaming) within a Transaction.
	TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error
	// *
	// Savepoint Control within a Transaction.
	// Enables nested transaction boundaries (SAVEPOINT, RELEASE, ROLLBACK TO)
	// within an active Unary ID-Based transaction.
	TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error)
	// *
	// Transaction Commit.
	// Commits an active Unary ID-Based transaction and releases the connection
	// back to the shared LRU pool.
	CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Transaction Rollback.
	// Rolls back an active Unary ID-Based transaction and releases the connection
	// back to the shared LRU pool.
	RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error)
	// *
	// Atomic Script Execution.
	// Executes a predefined sequence of queries within a single transaction
	// atomically. Handled completely server-side to minimize network latency
	// between statements.
	ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error)
	// *
	// Typed Read Endpoint (Unary).
	// Automatically routed to a Read-Only replica connection for ROLE_READ_ONLY
	// users.
	TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Typed Write Endpoint (Unary DML).
	// Uses the global shared LRU connection pool, strictly routing to a
	// Read-Write connection.
	TypedExec(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Typed Read Endpoint (Streaming).
	// Routes to the global Read-Only or Read-Write LRU connection depending on
	// user role.
	TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error
	// *
	// Typed Read Endpoint within a Transaction.
	TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error)
	// *
	// Typed Write Endpoint within a Transaction.
	// Denied on Read-Only transactions.
	TypedTransactionExec(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error)
	// *
	// Streaming Interface.
	// Yields partitioned tenant data blocks over a managed stream.
	TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error
	// *
	// Introspection: Query Plan Explanation.
	// Returns the EXPLAIN QUERY PLAN breakdown for a given statement without
	// running the statement itself.
	Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Typed Introspection: Query Plan Explanation.
	// Provides the EXPLAIN QUERY PLAN breakdown using strictly-typed parameters.
	TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error)
	// *
	// Database Introspection: List Tables.
	// Returns a list of all table names currently present in the target database.
	ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error)
	// *
	// Database Introspection: Get Table Schema.
	// Returns the structural schema definitions for a specific table.
	GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error)
	// *
	// Database Introspection: Get Database Schema.
	// Returns the structural schema definitions for the entire underlying
	// database.
	GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error)
	// *
	// Maintenance: Vacuum.
	// Rebuilds the database file, repacking it into a minimal amount of disk
	// space.
	Vacuum(context.Context, *connect.Request[v1.VacuumRequest]) (*connect.Response[v1.VacuumResponse], error)
	// *
	// Maintenance: Checkpoint.
	// Synchronizes the write-ahead log (WAL) with the main database file.
	Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.CheckpointResponse], error)
	// *
	// Maintenance: Integrity Check.
	// Runs PRAGMA integrity_check to scan for out-of-order records, missing
	// pages, or corruption.
	IntegrityCheck(context.Context, *connect.Request[v1.IntegrityCheckRequest]) (*connect.Response[v1.IntegrityCheckResponse], error)
	// *
	// Maintenance: Attach Database.
	// Dynamically mounts a secondary database into the current tenant's namespace
	// context.
	AttachDatabase(context.Context, *connect.Request[v1.AttachDatabaseRequest]) (*connect.Response[v1.AttachDatabaseResponse], error)
	// *
	// Maintenance: Detach Database.
	// Safely detaches a previously attached secondary database from the active
	// context.
	DetachDatabase(context.Context, *connect.Request[v1.DetachDatabaseRequest]) (*connect.Response[v1.DetachDatabaseResponse], error)
	// *
	// Extensions: List.
	// Returns a catalog of available and loaded SQLite extensions.
	ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error)
	// *
	// Extensions: Load.
	// Dynamically loads a compatible SQLite extension into the target database.
	LoadExtension(context.Context, *connect.Request[v1.LoadExtensionRequest]) (*connect.Response[v1.LoadExtensionResponse], error)
}

// NewDatabaseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatabaseServiceHandler(svc DatabaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	databaseServiceMethods := v1.File_sqlrpc_v1_db_service_proto.Services().ByName("DatabaseService").Methods()
	databaseServiceQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(databaseServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecHandler := connect.NewUnaryHandler(
		DatabaseServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(databaseServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceQueryStreamProcedure,
		svc.QueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("QueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionHandler := connect.NewBidiStreamHandler(
		DatabaseServiceTransactionProcedure,
		svc.Transaction,
		connect.WithSchema(databaseServiceMethods.ByName("Transaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceBeginTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceBeginTransactionProcedure,
		svc.BeginTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("BeginTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionQueryProcedure,
		svc.TransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionExecHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionExecProcedure,
		svc.TransactionExec,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionExec")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTransactionQueryStreamProcedure,
		svc.TransactionQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTransactionSavepointHandler := connect.NewUnaryHandler(
		DatabaseServiceTransactionSavepointProcedure,
		svc.TransactionSavepoint,
		connect.WithSchema(databaseServiceMethods.ByName("TransactionSavepoint")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCommitTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceCommitTransactionProcedure,
		svc.CommitTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("CommitTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceRollbackTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceRollbackTransactionProcedure,
		svc.RollbackTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("RollbackTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExecuteTransactionHandler := connect.NewUnaryHandler(
		DatabaseServiceExecuteTransactionProcedure,
		svc.ExecuteTransaction,
		connect.WithSchema(databaseServiceMethods.ByName("ExecuteTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedQueryProcedure,
		svc.TypedQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TypedQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedExecHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedExecProcedure,
		svc.TypedExec,
		connect.WithSchema(databaseServiceMethods.ByName("TypedExec")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTypedQueryStreamProcedure,
		svc.TypedQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TypedQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedTransactionQueryHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedTransactionQueryProcedure,
		svc.TypedTransactionQuery,
		connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQuery")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedTransactionExecHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedTransactionExecProcedure,
		svc.TypedTransactionExec,
		connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionExec")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedTransactionQueryStreamHandler := connect.NewServerStreamHandler(
		DatabaseServiceTypedTransactionQueryStreamProcedure,
		svc.TypedTransactionQueryStream,
		connect.WithSchema(databaseServiceMethods.ByName("TypedTransactionQueryStream")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceExplainHandler := connect.NewUnaryHandler(
		DatabaseServiceExplainProcedure,
		svc.Explain,
		connect.WithSchema(databaseServiceMethods.ByName("Explain")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceTypedExplainHandler := connect.NewUnaryHandler(
		DatabaseServiceTypedExplainProcedure,
		svc.TypedExplain,
		connect.WithSchema(databaseServiceMethods.ByName("TypedExplain")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListTablesHandler := connect.NewUnaryHandler(
		DatabaseServiceListTablesProcedure,
		svc.ListTables,
		connect.WithSchema(databaseServiceMethods.ByName("ListTables")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetTableSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceGetTableSchemaProcedure,
		svc.GetTableSchema,
		connect.WithSchema(databaseServiceMethods.ByName("GetTableSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceGetDatabaseSchemaHandler := connect.NewUnaryHandler(
		DatabaseServiceGetDatabaseSchemaProcedure,
		svc.GetDatabaseSchema,
		connect.WithSchema(databaseServiceMethods.ByName("GetDatabaseSchema")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceVacuumHandler := connect.NewUnaryHandler(
		DatabaseServiceVacuumProcedure,
		svc.Vacuum,
		connect.WithSchema(databaseServiceMethods.ByName("Vacuum")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceCheckpointHandler := connect.NewUnaryHandler(
		DatabaseServiceCheckpointProcedure,
		svc.Checkpoint,
		connect.WithSchema(databaseServiceMethods.ByName("Checkpoint")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceIntegrityCheckHandler := connect.NewUnaryHandler(
		DatabaseServiceIntegrityCheckProcedure,
		svc.IntegrityCheck,
		connect.WithSchema(databaseServiceMethods.ByName("IntegrityCheck")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceAttachDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceAttachDatabaseProcedure,
		svc.AttachDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("AttachDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceDetachDatabaseHandler := connect.NewUnaryHandler(
		DatabaseServiceDetachDatabaseProcedure,
		svc.DetachDatabase,
		connect.WithSchema(databaseServiceMethods.ByName("DetachDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceListExtensionsHandler := connect.NewUnaryHandler(
		DatabaseServiceListExtensionsProcedure,
		svc.ListExtensions,
		connect.WithSchema(databaseServiceMethods.ByName("ListExtensions")),
		connect.WithHandlerOptions(opts...),
	)
	databaseServiceLoadExtensionHandler := connect.NewUnaryHandler(
		DatabaseServiceLoadExtensionProcedure,
		svc.LoadExtension,
		connect.WithSchema(databaseServiceMethods.ByName("LoadExtension")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sqlrpc.v1.DatabaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatabaseServiceQueryProcedure:
			databaseServiceQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceExecProcedure:
			databaseServiceExecHandler.ServeHTTP(w, r)
		case DatabaseServiceQueryStreamProcedure:
			databaseServiceQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionProcedure:
			databaseServiceTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceBeginTransactionProcedure:
			databaseServiceBeginTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryProcedure:
			databaseServiceTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionExecProcedure:
			databaseServiceTransactionExecHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionQueryStreamProcedure:
			databaseServiceTransactionQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTransactionSavepointProcedure:
			databaseServiceTransactionSavepointHandler.ServeHTTP(w, r)
		case DatabaseServiceCommitTransactionProcedure:
			databaseServiceCommitTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceRollbackTransactionProcedure:
			databaseServiceRollbackTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceExecuteTransactionProcedure:
			databaseServiceExecuteTransactionHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedQueryProcedure:
			databaseServiceTypedQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedExecProcedure:
			databaseServiceTypedExecHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedQueryStreamProcedure:
			databaseServiceTypedQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedTransactionQueryProcedure:
			databaseServiceTypedTransactionQueryHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedTransactionExecProcedure:
			databaseServiceTypedTransactionExecHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedTransactionQueryStreamProcedure:
			databaseServiceTypedTransactionQueryStreamHandler.ServeHTTP(w, r)
		case DatabaseServiceExplainProcedure:
			databaseServiceExplainHandler.ServeHTTP(w, r)
		case DatabaseServiceTypedExplainProcedure:
			databaseServiceTypedExplainHandler.ServeHTTP(w, r)
		case DatabaseServiceListTablesProcedure:
			databaseServiceListTablesHandler.ServeHTTP(w, r)
		case DatabaseServiceGetTableSchemaProcedure:
			databaseServiceGetTableSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceGetDatabaseSchemaProcedure:
			databaseServiceGetDatabaseSchemaHandler.ServeHTTP(w, r)
		case DatabaseServiceVacuumProcedure:
			databaseServiceVacuumHandler.ServeHTTP(w, r)
		case DatabaseServiceCheckpointProcedure:
			databaseServiceCheckpointHandler.ServeHTTP(w, r)
		case DatabaseServiceIntegrityCheckProcedure:
			databaseServiceIntegrityCheckHandler.ServeHTTP(w, r)
		case DatabaseServiceAttachDatabaseProcedure:
			databaseServiceAttachDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceDetachDatabaseProcedure:
			databaseServiceDetachDatabaseHandler.ServeHTTP(w, r)
		case DatabaseServiceListExtensionsProcedure:
			databaseServiceListExtensionsHandler.ServeHTTP(w, r)
		case DatabaseServiceLoadExtensionProcedure:
			databaseServiceLoadExtensionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatabaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatabaseServiceHandler struct{}

func (UnimplementedDatabaseServiceHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Query is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Exec(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Exec is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) QueryStream(context.Context, *connect.Request[v1.QueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.QueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Transaction(context.Context, *connect.BidiStream[v1.TransactionRequest, v1.TransactionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Transaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) BeginTransaction(context.Context, *connect.Request[v1.BeginTransactionRequest]) (*connect.Response[v1.BeginTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.BeginTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQuery(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.QueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionExec(context.Context, *connect.Request[v1.TransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TransactionExec is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionQueryStream(context.Context, *connect.Request[v1.TransactionQueryRequest], *connect.ServerStream[v1.QueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TransactionQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TransactionSavepoint(context.Context, *connect.Request[v1.TransactionSavepointRequest]) (*connect.Response[v1.SavepointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TransactionSavepoint is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) CommitTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.CommitTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) RollbackTransaction(context.Context, *connect.Request[v1.TransactionControlRequest]) (*connect.Response[v1.TransactionControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.RollbackTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ExecuteTransaction(context.Context, *connect.Request[v1.ExecuteTransactionRequest]) (*connect.Response[v1.ExecuteTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.ExecuteTransaction is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedQuery(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedExec(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedExec is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedQueryStream(context.Context, *connect.Request[v1.TypedQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedTransactionQuery(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.TypedQueryResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedTransactionQuery is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedTransactionExec(context.Context, *connect.Request[v1.TypedTransactionQueryRequest]) (*connect.Response[v1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedTransactionExec is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedTransactionQueryStream(context.Context, *connect.Request[v1.TypedTransactionQueryRequest], *connect.ServerStream[v1.TypedQueryResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedTransactionQueryStream is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Explain(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Explain is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) TypedExplain(context.Context, *connect.Request[v1.TypedQueryRequest]) (*connect.Response[v1.ExplainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.TypedExplain is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListTables(context.Context, *connect.Request[v1.ListTablesRequest]) (*connect.Response[v1.ListTablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.ListTables is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetTableSchema(context.Context, *connect.Request[v1.GetTableSchemaRequest]) (*connect.Response[v1.TableSchema], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.GetTableSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) GetDatabaseSchema(context.Context, *connect.Request[v1.GetDatabaseSchemaRequest]) (*connect.Response[v1.DatabaseSchema], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.GetDatabaseSchema is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Vacuum(context.Context, *connect.Request[v1.VacuumRequest]) (*connect.Response[v1.VacuumResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Vacuum is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) Checkpoint(context.Context, *connect.Request[v1.CheckpointRequest]) (*connect.Response[v1.CheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.Checkpoint is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) IntegrityCheck(context.Context, *connect.Request[v1.IntegrityCheckRequest]) (*connect.Response[v1.IntegrityCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.IntegrityCheck is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) AttachDatabase(context.Context, *connect.Request[v1.AttachDatabaseRequest]) (*connect.Response[v1.AttachDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.AttachDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) DetachDatabase(context.Context, *connect.Request[v1.DetachDatabaseRequest]) (*connect.Response[v1.DetachDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.DetachDatabase is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) ListExtensions(context.Context, *connect.Request[v1.ListExtensionsRequest]) (*connect.Response[v1.ListExtensionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.ListExtensions is not implemented"))
}

func (UnimplementedDatabaseServiceHandler) LoadExtension(context.Context, *connect.Request[v1.LoadExtensionRequest]) (*connect.Response[v1.LoadExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sqlrpc.v1.DatabaseService.LoadExtension is not implemented"))
}
